#ifndef __PPTX_ST_PARAMETER_ID_H__
#define __PPTX_ST_PARAMETER_ID_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef enum pptx_st_parameter_id_token_enum {
    ST_PARAMETER_ID_TX_ANCHOR_VERT,
    ST_PARAMETER_ID_TX_DIR,
    ST_PARAMETER_ID_PYRA_ACCT_TX_NODE,
    ST_PARAMETER_ID_AUTO_TX_ROT,
    ST_PARAMETER_ID_SRC_NODE,
    ST_PARAMETER_ID_LIN_DIR,
    ST_PARAMETER_ID_HORZ_ALIGN,
    ST_PARAMETER_ID_CH_ALIGN,
    ST_PARAMETER_ID_NODE_HORZ_ALIGN,
    ST_PARAMETER_ID_TX_BL_DIR,
    ST_PARAMETER_ID_HIER_ALIGN,
    ST_PARAMETER_ID_LN_SP_PAR,
    ST_PARAMETER_ID_ST_BULLET_LVL,
    ST_PARAMETER_ID_LN_SP_CH,
    ST_PARAMETER_ID_ROT_PATH,
    ST_PARAMETER_ID_SHP_TX_LTRALIGN_CH,
    ST_PARAMETER_ID_TX_ANCHOR_HORZ,
    ST_PARAMETER_ID_LN_SP_AF_PAR_P,
    ST_PARAMETER_ID_LN_SP_AF_CH_P,
    ST_PARAMETER_ID_RT_SHORT_DIST,
    ST_PARAMETER_ID_END_STY,
    ST_PARAMETER_ID_TX_ANCHOR_VERT_CH,
    ST_PARAMETER_ID_PYRA_ACCT_POS,
    ST_PARAMETER_ID_ALIGN_TX,
    ST_PARAMETER_ID_BKPT,
    ST_PARAMETER_ID_PAR_TX_RTLALIGN,
    ST_PARAMETER_ID_NODE_VERT_ALIGN,
    ST_PARAMETER_ID_PYRA_LVL_NODE,
    ST_PARAMETER_ID_SEC_LIN_DIR,
    ST_PARAMETER_ID_BK_PT_FIXED_VAL,
    ST_PARAMETER_ID_VERT_ALIGN,
    ST_PARAMETER_ID_BEG_STY,
    ST_PARAMETER_ID_CH_DIR,
    ST_PARAMETER_ID_NIL,
    ST_PARAMETER_ID_SPAN_ANG,
    ST_PARAMETER_ID_PYRA_ACCT_TX_MAR,
    ST_PARAMETER_ID_PAR_TX_LTRALIGN,
    ST_PARAMETER_ID_SEC_CH_ALIGN,
    ST_PARAMETER_ID_PYRA_ACCT_BKGD_NODE,
    ST_PARAMETER_ID_ST_ANG,
    ST_PARAMETER_ID_GR_DIR,
    ST_PARAMETER_ID_END_PTS,
    ST_PARAMETER_ID_CONT_DIR,
    ST_PARAMETER_ID_BEND_PT,
    ST_PARAMETER_ID_ST_ELEM,
    ST_PARAMETER_ID_DIM,
    ST_PARAMETER_ID_FLOW_DIR,
    ST_PARAMETER_ID_OFF,
    ST_PARAMETER_ID_TX_ANCHOR_HORZ_CH,
    ST_PARAMETER_ID_SHP_TX_RTLALIGN_CH,
    ST_PARAMETER_ID_CONN_ROUT,
    ST_PARAMETER_ID_BEG_PTS,
    ST_PARAMETER_ID_AR,
    ST_PARAMETER_ID_FALLBACK,
    ST_PARAMETER_ID_DST_NODE,
    ST_PARAMETER_ID_CTR_SHP_MAP
} pptx_st_parameter_id_token_enum;

pptx_st_parameter_id_token_enum pptx_get_st_parameter_id(xmlNode *node, const xmlChar *property);

#endif /* __PPTX_ST_PARAMETER_ID_H__ */
