#ifndef __PPTX_CT_P_TLANIMATE_BEHAVIOR_H__
#define __PPTX_CT_P_TLANIMATE_BEHAVIOR_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_p_tlcommon_behavior_data_s pptx_ct_p_tlcommon_behavior_data;
typedef struct pptx_ct_p_tltime_animate_value_list_s pptx_ct_p_tltime_animate_value_list;
typedef enum pptx_st_tlanimate_behavior_calc_mode_token_enum pptx_st_tlanimate_behavior_calc_mode_token_enum;
typedef enum pptx_st_tlanimate_behavior_value_type_token_enum pptx_st_tlanimate_behavior_value_type_token_enum;

typedef struct pptx_ct_p_tlanimate_behavior_s pptx_ct_p_tlanimate_behavior;
pptx_ct_p_tlanimate_behavior *pptx_ct_p_tlanimate_behavior_new(xmlNode *node);
void pptx_ct_p_tlanimate_behavior_free(pptx_ct_p_tlanimate_behavior *obj);
pptx_ct_p_tlcommon_behavior_data *pptx_ct_p_tlanimate_behavior_get_c_bhvr(const pptx_ct_p_tlanimate_behavior *const obj);
pptx_ct_p_tltime_animate_value_list *pptx_ct_p_tlanimate_behavior_get_tav_lst(const pptx_ct_p_tlanimate_behavior *const obj);
pptx_string pptx_ct_p_tlanimate_behavior_get_by(const pptx_ct_p_tlanimate_behavior *const obj);
pptx_string pptx_ct_p_tlanimate_behavior_get_from(const pptx_ct_p_tlanimate_behavior *const obj);
pptx_string pptx_ct_p_tlanimate_behavior_get_to(const pptx_ct_p_tlanimate_behavior *const obj);
pptx_st_tlanimate_behavior_calc_mode_token_enum pptx_ct_p_tlanimate_behavior_get_calcmode(const pptx_ct_p_tlanimate_behavior *const obj);
pptx_st_tlanimate_behavior_value_type_token_enum pptx_ct_p_tlanimate_behavior_get_value_type(const pptx_ct_p_tlanimate_behavior *const obj);
int32_t pptx_ct_p_tlanimate_behavior_get_index(pptx_ct_p_tlanimate_behavior *obj);

#endif /* __PPTX_CT_P_TLANIMATE_BEHAVIOR_H__ */
