#ifndef __PPTX_CT_A_TEXT_PARAGRAPH_PROPERTIES_H__
#define __PPTX_CT_A_TEXT_PARAGRAPH_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_text_spacing_s pptx_ct_a_text_spacing;
typedef struct pptx_ct_a_text_bullet_color_follow_text_s pptx_ct_a_text_bullet_color_follow_text;
typedef struct pptx_ct_a_color_s pptx_ct_a_color;
typedef struct pptx_ct_a_text_bullet_size_follow_text_s pptx_ct_a_text_bullet_size_follow_text;
typedef struct pptx_ct_a_text_bullet_size_percent_s pptx_ct_a_text_bullet_size_percent;
typedef struct pptx_ct_a_text_bullet_size_point_s pptx_ct_a_text_bullet_size_point;
typedef struct pptx_ct_a_text_bullet_typeface_follow_text_s pptx_ct_a_text_bullet_typeface_follow_text;
typedef struct pptx_ct_a_text_font_s pptx_ct_a_text_font;
typedef struct pptx_ct_a_text_no_bullet_s pptx_ct_a_text_no_bullet;
typedef struct pptx_ct_a_text_autonumber_bullet_s pptx_ct_a_text_autonumber_bullet;
typedef struct pptx_ct_a_text_char_bullet_s pptx_ct_a_text_char_bullet;
typedef struct pptx_ct_a_text_blip_bullet_s pptx_ct_a_text_blip_bullet;
typedef struct pptx_ct_a_text_tab_stop_list_s pptx_ct_a_text_tab_stop_list;
typedef struct pptx_ct_a_text_character_properties_s pptx_ct_a_text_character_properties;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;
typedef enum pptx_st_text_align_type_token_enum pptx_st_text_align_type_token_enum;
typedef enum pptx_st_text_font_align_type_token_enum pptx_st_text_font_align_type_token_enum;

typedef struct pptx_ct_a_text_paragraph_properties_s pptx_ct_a_text_paragraph_properties;
pptx_ct_a_text_paragraph_properties *pptx_ct_a_text_paragraph_properties_new(xmlNode *node);
void pptx_ct_a_text_paragraph_properties_free(pptx_ct_a_text_paragraph_properties *obj);
pptx_ct_a_text_spacing *pptx_ct_a_text_paragraph_properties_get_ln_spc(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_spacing *pptx_ct_a_text_paragraph_properties_get_spc_bef(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_spacing *pptx_ct_a_text_paragraph_properties_get_spc_aft(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_bullet_color_follow_text *pptx_ct_a_text_paragraph_properties_get_text_bullet_color_bu_clr_tx(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_color *pptx_ct_a_text_paragraph_properties_get_text_bullet_color_bu_clr(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_bullet_size_follow_text *pptx_ct_a_text_paragraph_properties_get_text_bullet_size_bu_sz_tx(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_bullet_size_percent *pptx_ct_a_text_paragraph_properties_get_text_bullet_size_bu_sz_pct(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_bullet_size_point *pptx_ct_a_text_paragraph_properties_get_text_bullet_size_bu_sz_pts(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_bullet_typeface_follow_text *pptx_ct_a_text_paragraph_properties_get_text_bullet_typeface_bu_font_tx(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_font *pptx_ct_a_text_paragraph_properties_get_text_bullet_typeface_bu_font(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_no_bullet *pptx_ct_a_text_paragraph_properties_get_text_bullet_bu_none(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_autonumber_bullet *pptx_ct_a_text_paragraph_properties_get_text_bullet_bu_auto_num(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_char_bullet *pptx_ct_a_text_paragraph_properties_get_text_bullet_bu_char(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_blip_bullet *pptx_ct_a_text_paragraph_properties_get_text_bullet_bu_blip(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_tab_stop_list *pptx_ct_a_text_paragraph_properties_get_tab_lst(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_text_character_properties *pptx_ct_a_text_paragraph_properties_get_def_rpr(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_text_paragraph_properties_get_ext_lst(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_int pptx_ct_a_text_paragraph_properties_get_mar_l(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_int pptx_ct_a_text_paragraph_properties_get_mar_r(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_int pptx_ct_a_text_paragraph_properties_get_lvl(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_int pptx_ct_a_text_paragraph_properties_get_indent(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_st_text_align_type_token_enum pptx_ct_a_text_paragraph_properties_get_algn(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_string pptx_ct_a_text_paragraph_properties_get_def_tab_sz(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_bool pptx_ct_a_text_paragraph_properties_get_rtl(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_bool pptx_ct_a_text_paragraph_properties_get_ea_ln_brk(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_st_text_font_align_type_token_enum pptx_ct_a_text_paragraph_properties_get_font_algn(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_bool pptx_ct_a_text_paragraph_properties_get_latin_ln_brk(const pptx_ct_a_text_paragraph_properties *const obj);
pptx_bool pptx_ct_a_text_paragraph_properties_get_hanging_punct(const pptx_ct_a_text_paragraph_properties *const obj);
int32_t pptx_ct_a_text_paragraph_properties_get_index(pptx_ct_a_text_paragraph_properties *obj);

#endif /* __PPTX_CT_A_TEXT_PARAGRAPH_PROPERTIES_H__ */
