#ifndef __PPTX_CT_A_OFFICE_STYLE_SHEET_H__
#define __PPTX_CT_A_OFFICE_STYLE_SHEET_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_base_styles_s pptx_ct_a_base_styles;
typedef struct pptx_ct_a_object_style_defaults_s pptx_ct_a_object_style_defaults;
typedef struct pptx_ct_a_color_scheme_list_s pptx_ct_a_color_scheme_list;
typedef struct pptx_ct_a_custom_color_list_s pptx_ct_a_custom_color_list;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;

typedef struct pptx_ct_a_office_style_sheet_s pptx_ct_a_office_style_sheet;
pptx_ct_a_office_style_sheet *pptx_ct_a_office_style_sheet_new(xmlNode *node);
void pptx_ct_a_office_style_sheet_free(pptx_ct_a_office_style_sheet *obj);
pptx_ct_a_base_styles *pptx_ct_a_office_style_sheet_get_theme_elements(const pptx_ct_a_office_style_sheet *const obj);
pptx_ct_a_object_style_defaults *pptx_ct_a_office_style_sheet_get_object_defaults(const pptx_ct_a_office_style_sheet *const obj);
pptx_ct_a_color_scheme_list *pptx_ct_a_office_style_sheet_get_extra_clr_scheme_lst(const pptx_ct_a_office_style_sheet *const obj);
pptx_ct_a_custom_color_list *pptx_ct_a_office_style_sheet_get_cust_clr_lst(const pptx_ct_a_office_style_sheet *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_office_style_sheet_get_ext_lst(const pptx_ct_a_office_style_sheet *const obj);
pptx_string pptx_ct_a_office_style_sheet_get_name(const pptx_ct_a_office_style_sheet *const obj);
int32_t pptx_ct_a_office_style_sheet_get_index(pptx_ct_a_office_style_sheet *obj);

#endif /* __PPTX_CT_A_OFFICE_STYLE_SHEET_H__ */
