#ifndef __PPTX_CT_A_GROUP_SHAPE_PROPERTIES_H__
#define __PPTX_CT_A_GROUP_SHAPE_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_group_transform_2d_s pptx_ct_a_group_transform_2d;
typedef struct pptx_ct_a_no_fill_properties_s pptx_ct_a_no_fill_properties;
typedef struct pptx_ct_a_solid_color_fill_properties_s pptx_ct_a_solid_color_fill_properties;
typedef struct pptx_ct_a_gradient_fill_properties_s pptx_ct_a_gradient_fill_properties;
typedef struct pptx_ct_a_blip_fill_properties_s pptx_ct_a_blip_fill_properties;
typedef struct pptx_ct_a_pattern_fill_properties_s pptx_ct_a_pattern_fill_properties;
typedef struct pptx_ct_a_group_fill_properties_s pptx_ct_a_group_fill_properties;
typedef struct pptx_ct_a_effect_list_s pptx_ct_a_effect_list;
typedef struct pptx_ct_a_effect_container_s pptx_ct_a_effect_container;
typedef struct pptx_ct_a_scene_3d_s pptx_ct_a_scene_3d;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;
typedef enum pptx_st_black_white_mode_token_enum pptx_st_black_white_mode_token_enum;

typedef struct pptx_ct_a_group_shape_properties_s pptx_ct_a_group_shape_properties;
pptx_ct_a_group_shape_properties *pptx_ct_a_group_shape_properties_new(xmlNode *node);
void pptx_ct_a_group_shape_properties_free(pptx_ct_a_group_shape_properties *obj);
pptx_ct_a_group_transform_2d *pptx_ct_a_group_shape_properties_get_xfrm(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_no_fill_properties *pptx_ct_a_group_shape_properties_get_fill_properties_no_fill(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_solid_color_fill_properties *pptx_ct_a_group_shape_properties_get_fill_properties_solid_fill(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_gradient_fill_properties *pptx_ct_a_group_shape_properties_get_fill_properties_grad_fill(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_blip_fill_properties *pptx_ct_a_group_shape_properties_get_fill_properties_blip_fill(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_pattern_fill_properties *pptx_ct_a_group_shape_properties_get_fill_properties_patt_fill(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_group_fill_properties *pptx_ct_a_group_shape_properties_get_fill_properties_grp_fill(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_effect_list *pptx_ct_a_group_shape_properties_get_effect_properties_effect_lst(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_effect_container *pptx_ct_a_group_shape_properties_get_effect_properties_effect_dag(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_scene_3d *pptx_ct_a_group_shape_properties_get_scene3d(const pptx_ct_a_group_shape_properties *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_group_shape_properties_get_ext_lst(const pptx_ct_a_group_shape_properties *const obj);
pptx_st_black_white_mode_token_enum pptx_ct_a_group_shape_properties_get_bw_mode(const pptx_ct_a_group_shape_properties *const obj);
int32_t pptx_ct_a_group_shape_properties_get_index(pptx_ct_a_group_shape_properties *obj);

#endif /* __PPTX_CT_A_GROUP_SHAPE_PROPERTIES_H__ */
