#ifndef __PPTX_CT_P_TLTIME_NODE_SEQUENCE_H__
#define __PPTX_CT_P_TLTIME_NODE_SEQUENCE_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_p_tlcommon_time_node_data_s pptx_ct_p_tlcommon_time_node_data;
typedef struct pptx_ct_p_tltime_condition_list_s pptx_ct_p_tltime_condition_list;
typedef enum pptx_st_tlprevious_action_type_token_enum pptx_st_tlprevious_action_type_token_enum;
typedef enum pptx_st_tlnext_action_type_token_enum pptx_st_tlnext_action_type_token_enum;

typedef struct pptx_ct_p_tltime_node_sequence_s pptx_ct_p_tltime_node_sequence;
pptx_ct_p_tltime_node_sequence *pptx_ct_p_tltime_node_sequence_new(xmlNode *node);
void pptx_ct_p_tltime_node_sequence_free(pptx_ct_p_tltime_node_sequence *obj);
pptx_ct_p_tlcommon_time_node_data *pptx_ct_p_tltime_node_sequence_get_c_tn(const pptx_ct_p_tltime_node_sequence *const obj);
pptx_ct_p_tltime_condition_list *pptx_ct_p_tltime_node_sequence_get_prev_cond_lst(const pptx_ct_p_tltime_node_sequence *const obj);
pptx_ct_p_tltime_condition_list *pptx_ct_p_tltime_node_sequence_get_next_cond_lst(const pptx_ct_p_tltime_node_sequence *const obj);
pptx_bool pptx_ct_p_tltime_node_sequence_get_concurrent(const pptx_ct_p_tltime_node_sequence *const obj);
pptx_st_tlprevious_action_type_token_enum pptx_ct_p_tltime_node_sequence_get_prev_ac(const pptx_ct_p_tltime_node_sequence *const obj);
pptx_st_tlnext_action_type_token_enum pptx_ct_p_tltime_node_sequence_get_next_ac(const pptx_ct_p_tltime_node_sequence *const obj);
int32_t pptx_ct_p_tltime_node_sequence_get_index(pptx_ct_p_tltime_node_sequence *obj);

#endif /* __PPTX_CT_P_TLTIME_NODE_SEQUENCE_H__ */
