#ifndef __PPTX_CT_P_PRESENTATION_PROPERTIES_H__
#define __PPTX_CT_P_PRESENTATION_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_p_html_publish_properties_s pptx_ct_p_html_publish_properties;
typedef struct pptx_ct_p_web_properties_s pptx_ct_p_web_properties;
typedef struct pptx_ct_p_print_properties_s pptx_ct_p_print_properties;
typedef struct pptx_ct_p_show_properties_s pptx_ct_p_show_properties;
typedef struct pptx_ct_a_color_mru_s pptx_ct_a_color_mru;
typedef struct pptx_ct_p_extension_list_s pptx_ct_p_extension_list;

typedef struct pptx_ct_p_presentation_properties_s pptx_ct_p_presentation_properties;
pptx_ct_p_presentation_properties *pptx_ct_p_presentation_properties_new(xmlNode *node);
void pptx_ct_p_presentation_properties_free(pptx_ct_p_presentation_properties *obj);
pptx_ct_p_html_publish_properties *pptx_ct_p_presentation_properties_get_html_pub_pr(const pptx_ct_p_presentation_properties *const obj);
pptx_ct_p_web_properties *pptx_ct_p_presentation_properties_get_web_pr(const pptx_ct_p_presentation_properties *const obj);
pptx_ct_p_print_properties *pptx_ct_p_presentation_properties_get_prn_pr(const pptx_ct_p_presentation_properties *const obj);
pptx_ct_p_show_properties *pptx_ct_p_presentation_properties_get_show_pr(const pptx_ct_p_presentation_properties *const obj);
pptx_ct_a_color_mru *pptx_ct_p_presentation_properties_get_clr_mru(const pptx_ct_p_presentation_properties *const obj);
pptx_ct_p_extension_list *pptx_ct_p_presentation_properties_get_ext_lst(const pptx_ct_p_presentation_properties *const obj);
int32_t pptx_ct_p_presentation_properties_get_index(pptx_ct_p_presentation_properties *obj);

#endif /* __PPTX_CT_P_PRESENTATION_PROPERTIES_H__ */
