#ifndef __PPTX_CT_A_DEFAULT_SHAPE_DEFINITION_H__
#define __PPTX_CT_A_DEFAULT_SHAPE_DEFINITION_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_shape_properties_s pptx_ct_a_shape_properties;
typedef struct pptx_ct_a_text_body_properties_s pptx_ct_a_text_body_properties;
typedef struct pptx_ct_a_text_list_style_s pptx_ct_a_text_list_style;
typedef struct pptx_ct_a_shape_style_s pptx_ct_a_shape_style;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;

typedef struct pptx_ct_a_default_shape_definition_s pptx_ct_a_default_shape_definition;
pptx_ct_a_default_shape_definition *pptx_ct_a_default_shape_definition_new(xmlNode *node);
void pptx_ct_a_default_shape_definition_free(pptx_ct_a_default_shape_definition *obj);
pptx_ct_a_shape_properties *pptx_ct_a_default_shape_definition_get_sp_pr(const pptx_ct_a_default_shape_definition *const obj);
pptx_ct_a_text_body_properties *pptx_ct_a_default_shape_definition_get_body_pr(const pptx_ct_a_default_shape_definition *const obj);
pptx_ct_a_text_list_style *pptx_ct_a_default_shape_definition_get_lst_style(const pptx_ct_a_default_shape_definition *const obj);
pptx_ct_a_shape_style *pptx_ct_a_default_shape_definition_get_style(const pptx_ct_a_default_shape_definition *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_default_shape_definition_get_ext_lst(const pptx_ct_a_default_shape_definition *const obj);
int32_t pptx_ct_a_default_shape_definition_get_index(pptx_ct_a_default_shape_definition *obj);

#endif /* __PPTX_CT_A_DEFAULT_SHAPE_DEFINITION_H__ */
