#ifndef __PPTX_CT_A_TEXT_BODY_PROPERTIES_H__
#define __PPTX_CT_A_TEXT_BODY_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_preset_text_shape_s pptx_ct_a_preset_text_shape;
typedef struct pptx_ct_a_text_no_autofit_s pptx_ct_a_text_no_autofit;
typedef struct pptx_ct_a_text_normal_autofit_s pptx_ct_a_text_normal_autofit;
typedef struct pptx_ct_a_text_shape_autofit_s pptx_ct_a_text_shape_autofit;
typedef struct pptx_ct_a_scene_3d_s pptx_ct_a_scene_3d;
typedef struct pptx_ct_a_shape_3d_s pptx_ct_a_shape_3d;
typedef struct pptx_ct_a_flat_text_s pptx_ct_a_flat_text;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;
typedef enum pptx_st_text_vert_overflow_type_token_enum pptx_st_text_vert_overflow_type_token_enum;
typedef enum pptx_st_text_horz_overflow_type_token_enum pptx_st_text_horz_overflow_type_token_enum;
typedef enum pptx_st_text_vertical_type_token_enum pptx_st_text_vertical_type_token_enum;
typedef enum pptx_st_text_wrapping_type_token_enum pptx_st_text_wrapping_type_token_enum;
typedef enum pptx_st_text_anchoring_type_token_enum pptx_st_text_anchoring_type_token_enum;

typedef struct pptx_ct_a_text_body_properties_s pptx_ct_a_text_body_properties;
pptx_ct_a_text_body_properties *pptx_ct_a_text_body_properties_new(xmlNode *node);
void pptx_ct_a_text_body_properties_free(pptx_ct_a_text_body_properties *obj);
pptx_ct_a_preset_text_shape *pptx_ct_a_text_body_properties_get_prst_tx_warp(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_text_no_autofit *pptx_ct_a_text_body_properties_get_text_autofit_no_autofit(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_text_normal_autofit *pptx_ct_a_text_body_properties_get_text_autofit_norm_autofit(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_text_shape_autofit *pptx_ct_a_text_body_properties_get_text_autofit_sp_auto_fit(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_scene_3d *pptx_ct_a_text_body_properties_get_scene3d(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_shape_3d *pptx_ct_a_text_body_properties_get_text_3d_sp3d(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_flat_text *pptx_ct_a_text_body_properties_get_text_3d_flat_tx(const pptx_ct_a_text_body_properties *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_text_body_properties_get_ext_lst(const pptx_ct_a_text_body_properties *const obj);
pptx_int pptx_ct_a_text_body_properties_get_rot(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_spc_first_last_para(const pptx_ct_a_text_body_properties *const obj);
pptx_st_text_vert_overflow_type_token_enum pptx_ct_a_text_body_properties_get_vert_overflow(const pptx_ct_a_text_body_properties *const obj);
pptx_st_text_horz_overflow_type_token_enum pptx_ct_a_text_body_properties_get_horz_overflow(const pptx_ct_a_text_body_properties *const obj);
pptx_st_text_vertical_type_token_enum pptx_ct_a_text_body_properties_get_vert(const pptx_ct_a_text_body_properties *const obj);
pptx_st_text_wrapping_type_token_enum pptx_ct_a_text_body_properties_get_wrap(const pptx_ct_a_text_body_properties *const obj);
pptx_string pptx_ct_a_text_body_properties_get_l_ins(const pptx_ct_a_text_body_properties *const obj);
pptx_string pptx_ct_a_text_body_properties_get_t_ins(const pptx_ct_a_text_body_properties *const obj);
pptx_string pptx_ct_a_text_body_properties_get_r_ins(const pptx_ct_a_text_body_properties *const obj);
pptx_string pptx_ct_a_text_body_properties_get_b_ins(const pptx_ct_a_text_body_properties *const obj);
pptx_int pptx_ct_a_text_body_properties_get_num_col(const pptx_ct_a_text_body_properties *const obj);
pptx_int pptx_ct_a_text_body_properties_get_spc_col(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_rtl_col(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_from_word_art(const pptx_ct_a_text_body_properties *const obj);
pptx_st_text_anchoring_type_token_enum pptx_ct_a_text_body_properties_get_anchor(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_anchor_ctr(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_force_aa(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_upright(const pptx_ct_a_text_body_properties *const obj);
pptx_bool pptx_ct_a_text_body_properties_get_compat_ln_spc(const pptx_ct_a_text_body_properties *const obj);
int32_t pptx_ct_a_text_body_properties_get_index(pptx_ct_a_text_body_properties *obj);

#endif /* __PPTX_CT_A_TEXT_BODY_PROPERTIES_H__ */
