#ifndef __PPTX_CT_A_LINE_PROPERTIES_H__
#define __PPTX_CT_A_LINE_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_no_fill_properties_s pptx_ct_a_no_fill_properties;
typedef struct pptx_ct_a_solid_color_fill_properties_s pptx_ct_a_solid_color_fill_properties;
typedef struct pptx_ct_a_gradient_fill_properties_s pptx_ct_a_gradient_fill_properties;
typedef struct pptx_ct_a_pattern_fill_properties_s pptx_ct_a_pattern_fill_properties;
typedef struct pptx_ct_a_preset_line_dash_properties_s pptx_ct_a_preset_line_dash_properties;
typedef struct pptx_ct_a_dash_stop_list_s pptx_ct_a_dash_stop_list;
typedef struct pptx_ct_a_line_join_round_s pptx_ct_a_line_join_round;
typedef struct pptx_ct_a_line_join_bevel_s pptx_ct_a_line_join_bevel;
typedef struct pptx_ct_a_line_join_miter_properties_s pptx_ct_a_line_join_miter_properties;
typedef struct pptx_ct_a_line_end_properties_s pptx_ct_a_line_end_properties;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;
typedef enum pptx_st_line_cap_token_enum pptx_st_line_cap_token_enum;
typedef enum pptx_st_compound_line_token_enum pptx_st_compound_line_token_enum;
typedef enum pptx_st_pen_alignment_token_enum pptx_st_pen_alignment_token_enum;

typedef struct pptx_ct_a_line_properties_s pptx_ct_a_line_properties;
pptx_ct_a_line_properties *pptx_ct_a_line_properties_new(xmlNode *node);
void pptx_ct_a_line_properties_free(pptx_ct_a_line_properties *obj);
pptx_ct_a_no_fill_properties *pptx_ct_a_line_properties_get_line_fill_properties_no_fill(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_solid_color_fill_properties *pptx_ct_a_line_properties_get_line_fill_properties_solid_fill(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_gradient_fill_properties *pptx_ct_a_line_properties_get_line_fill_properties_grad_fill(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_pattern_fill_properties *pptx_ct_a_line_properties_get_line_fill_properties_patt_fill(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_preset_line_dash_properties *pptx_ct_a_line_properties_get_line_dash_properties_prst_dash(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_dash_stop_list *pptx_ct_a_line_properties_get_line_dash_properties_cust_dash(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_line_join_round *pptx_ct_a_line_properties_get_line_join_properties_round(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_line_join_bevel *pptx_ct_a_line_properties_get_line_join_properties_bevel(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_line_join_miter_properties *pptx_ct_a_line_properties_get_line_join_properties_miter(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_line_end_properties *pptx_ct_a_line_properties_get_head_end(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_line_end_properties *pptx_ct_a_line_properties_get_tail_end(const pptx_ct_a_line_properties *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_line_properties_get_ext_lst(const pptx_ct_a_line_properties *const obj);
pptx_int pptx_ct_a_line_properties_get_w(const pptx_ct_a_line_properties *const obj);
pptx_st_line_cap_token_enum pptx_ct_a_line_properties_get_cap(const pptx_ct_a_line_properties *const obj);
pptx_st_compound_line_token_enum pptx_ct_a_line_properties_get_cmpd(const pptx_ct_a_line_properties *const obj);
pptx_st_pen_alignment_token_enum pptx_ct_a_line_properties_get_algn(const pptx_ct_a_line_properties *const obj);
int32_t pptx_ct_a_line_properties_get_index(pptx_ct_a_line_properties *obj);

#endif /* __PPTX_CT_A_LINE_PROPERTIES_H__ */
