#ifndef __PPTX_CT_A_ANIMATION_GRAPHICAL_OBJECT_BUILD_PROPERTIES_H__
#define __PPTX_CT_A_ANIMATION_GRAPHICAL_OBJECT_BUILD_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_animation_dgm_build_properties_s pptx_ct_a_animation_dgm_build_properties;
typedef struct pptx_ct_a_animation_chart_build_properties_s pptx_ct_a_animation_chart_build_properties;

typedef struct pptx_ct_a_animation_graphical_object_build_properties_s pptx_ct_a_animation_graphical_object_build_properties;
pptx_ct_a_animation_graphical_object_build_properties *pptx_ct_a_animation_graphical_object_build_properties_new(xmlNode *node);
void pptx_ct_a_animation_graphical_object_build_properties_free(pptx_ct_a_animation_graphical_object_build_properties *obj);
pptx_ct_a_animation_dgm_build_properties *pptx_ct_a_animation_graphical_object_build_properties_get_bld_dgm(const pptx_ct_a_animation_graphical_object_build_properties *const obj);
pptx_ct_a_animation_chart_build_properties *pptx_ct_a_animation_graphical_object_build_properties_get_bld_chart(const pptx_ct_a_animation_graphical_object_build_properties *const obj);
int32_t pptx_ct_a_animation_graphical_object_build_properties_get_index(pptx_ct_a_animation_graphical_object_build_properties *obj);

#endif /* __PPTX_CT_A_ANIMATION_GRAPHICAL_OBJECT_BUILD_PROPERTIES_H__ */
