#ifndef __PPTX_ST_SLIDE_LAYOUT_TYPE_H__
#define __PPTX_ST_SLIDE_LAYOUT_TYPE_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef enum pptx_st_slide_layout_type_token_enum {
    ST_SLIDE_LAYOUT_TYPE_TX_OVER_OBJ,
    ST_SLIDE_LAYOUT_TYPE_TWO_OBJ_OVER_TX,
    ST_SLIDE_LAYOUT_TYPE_TX_AND_CLIP_ART,
    ST_SLIDE_LAYOUT_TYPE_BLANK,
    ST_SLIDE_LAYOUT_TYPE_PIC_TX,
    ST_SLIDE_LAYOUT_TYPE_TX_AND_OBJ,
    ST_SLIDE_LAYOUT_TYPE_TWO_OBJ_AND_TX,
    ST_SLIDE_LAYOUT_TYPE_TX,
    ST_SLIDE_LAYOUT_TYPE_TITLE,
    ST_SLIDE_LAYOUT_TYPE_CHART_AND_TX,
    ST_SLIDE_LAYOUT_TYPE_MEDIA_AND_TX,
    ST_SLIDE_LAYOUT_TYPE_CLIP_ART_AND_TX,
    ST_SLIDE_LAYOUT_TYPE_OBJ_AND_TX,
    ST_SLIDE_LAYOUT_TYPE_TX_AND_CHART,
    ST_SLIDE_LAYOUT_TYPE_TWO_COL_TX,
    ST_SLIDE_LAYOUT_TYPE_TX_AND_MEDIA,
    ST_SLIDE_LAYOUT_TYPE_CUST,
    ST_SLIDE_LAYOUT_TYPE_NIL,
    ST_SLIDE_LAYOUT_TYPE_TWO_TX_TWO_OBJ,
    ST_SLIDE_LAYOUT_TYPE_TITLE_ONLY,
    ST_SLIDE_LAYOUT_TYPE_CHART,
    ST_SLIDE_LAYOUT_TYPE_DGM,
    ST_SLIDE_LAYOUT_TYPE_OBJ_OVER_TX,
    ST_SLIDE_LAYOUT_TYPE_TBL,
    ST_SLIDE_LAYOUT_TYPE_SEC_HEAD,
    ST_SLIDE_LAYOUT_TYPE_CLIP_ART_AND_VERT_TX,
    ST_SLIDE_LAYOUT_TYPE_FOUR_OBJ,
    ST_SLIDE_LAYOUT_TYPE_OBJ_TX,
    ST_SLIDE_LAYOUT_TYPE_OBJ_AND_TWO_OBJ,
    ST_SLIDE_LAYOUT_TYPE_VERT_TX,
    ST_SLIDE_LAYOUT_TYPE_OBJ,
    ST_SLIDE_LAYOUT_TYPE_VERT_TITLE_AND_TX_OVER_CHART,
    ST_SLIDE_LAYOUT_TYPE_VERT_TITLE_AND_TX,
    ST_SLIDE_LAYOUT_TYPE_TWO_OBJ,
    ST_SLIDE_LAYOUT_TYPE_TX_AND_TWO_OBJ,
    ST_SLIDE_LAYOUT_TYPE_OBJ_ONLY,
    ST_SLIDE_LAYOUT_TYPE_TWO_OBJ_AND_OBJ
} pptx_st_slide_layout_type_token_enum;

pptx_st_slide_layout_type_token_enum pptx_get_st_slide_layout_type(xmlNode *node, const xmlChar *property);

#endif /* __PPTX_ST_SLIDE_LAYOUT_TYPE_H__ */
