#ifndef __PPTX_CT_P_APPLICATION_NON_VISUAL_DRAWING_PROPS_H__
#define __PPTX_CT_P_APPLICATION_NON_VISUAL_DRAWING_PROPS_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_p_placeholder_s pptx_ct_p_placeholder;
typedef struct pptx_ct_a_audio_cd_s pptx_ct_a_audio_cd;
typedef struct pptx_ct_a_embedded_wavaudio_file_s pptx_ct_a_embedded_wavaudio_file;
typedef struct pptx_ct_a_audio_file_s pptx_ct_a_audio_file;
typedef struct pptx_ct_a_video_file_s pptx_ct_a_video_file;
typedef struct pptx_ct_a_quick_time_file_s pptx_ct_a_quick_time_file;
typedef struct pptx_ct_p_customer_data_list_s pptx_ct_p_customer_data_list;
typedef struct pptx_ct_p_extension_list_s pptx_ct_p_extension_list;

typedef struct pptx_ct_p_application_non_visual_drawing_props_s pptx_ct_p_application_non_visual_drawing_props;
pptx_ct_p_application_non_visual_drawing_props *pptx_ct_p_application_non_visual_drawing_props_new(xmlNode *node);
void pptx_ct_p_application_non_visual_drawing_props_free(pptx_ct_p_application_non_visual_drawing_props *obj);
pptx_ct_p_placeholder *pptx_ct_p_application_non_visual_drawing_props_get_ph(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_a_audio_cd *pptx_ct_p_application_non_visual_drawing_props_get_media_audio_cd(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_a_embedded_wavaudio_file *pptx_ct_p_application_non_visual_drawing_props_get_media_wav_audio_file(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_a_audio_file *pptx_ct_p_application_non_visual_drawing_props_get_media_audio_file(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_a_video_file *pptx_ct_p_application_non_visual_drawing_props_get_media_video_file(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_a_quick_time_file *pptx_ct_p_application_non_visual_drawing_props_get_media_quick_time_file(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_p_customer_data_list *pptx_ct_p_application_non_visual_drawing_props_get_cust_data_lst(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_ct_p_extension_list *pptx_ct_p_application_non_visual_drawing_props_get_ext_lst(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_bool pptx_ct_p_application_non_visual_drawing_props_get_is_photo(const pptx_ct_p_application_non_visual_drawing_props *const obj);
pptx_bool pptx_ct_p_application_non_visual_drawing_props_get_user_drawn(const pptx_ct_p_application_non_visual_drawing_props *const obj);
int32_t pptx_ct_p_application_non_visual_drawing_props_get_index(pptx_ct_p_application_non_visual_drawing_props *obj);

#endif /* __PPTX_CT_P_APPLICATION_NON_VISUAL_DRAWING_PROPS_H__ */
