#ifndef __PPTX_ST_TEXT_AUTONUMBER_SCHEME_H__
#define __PPTX_ST_TEXT_AUTONUMBER_SCHEME_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef enum pptx_st_text_autonumber_scheme_token_enum {
    ST_TEXT_AUTONUMBER_SCHEME_ALPHA_UC_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_THAI_NUM_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_HINDI_NUM_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ALPHA_UC_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_THAI_NUM_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_CHS_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC_DB_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_THAI_ALPHA_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_JPN_KOR_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_CHT_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_ROMAN_UC_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_CHT_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_CIRCLE_NUM_DB_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_ROMAN_LC_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_CIRCLE_NUM_WD_WHITE_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_ALPHA_LC_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC_DB_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_CHS_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_THAI_NUM_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_JPN_CHS_DB_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_HEBREW2_MINUS,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_NIL,
    ST_TEXT_AUTONUMBER_SCHEME_THAI_ALPHA_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC1_MINUS,
    ST_TEXT_AUTONUMBER_SCHEME_ALPHA_LC_PAREN_BOTH,
    ST_TEXT_AUTONUMBER_SCHEME_ROMAN_LC_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_HINDI_ALPHA_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC_PLAIN,
    ST_TEXT_AUTONUMBER_SCHEME_HINDI_ALPHA1_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ROMAN_UC_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_EA1_JPN_KOR_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ROMAN_LC_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_ALPHA_LC_PERIOD,
    ST_TEXT_AUTONUMBER_SCHEME_ROMAN_UC_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_ALPHA_UC_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_THAI_ALPHA_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_HINDI_NUM_PAREN_R,
    ST_TEXT_AUTONUMBER_SCHEME_ARABIC2_MINUS,
    ST_TEXT_AUTONUMBER_SCHEME_CIRCLE_NUM_WD_BLACK_PLAIN
} pptx_st_text_autonumber_scheme_token_enum;

pptx_st_text_autonumber_scheme_token_enum pptx_get_st_text_autonumber_scheme(xmlNode *node, const xmlChar *property);

#endif /* __PPTX_ST_TEXT_AUTONUMBER_SCHEME_H__ */
