#ifndef __PPTX_CT_P_TLCOMMON_BEHAVIOR_DATA_H__
#define __PPTX_CT_P_TLCOMMON_BEHAVIOR_DATA_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_p_tlcommon_time_node_data_s pptx_ct_p_tlcommon_time_node_data;
typedef struct pptx_ct_p_tltime_target_element_s pptx_ct_p_tltime_target_element;
typedef struct pptx_ct_p_tlbehavior_attribute_name_list_s pptx_ct_p_tlbehavior_attribute_name_list;
typedef enum pptx_st_tlbehavior_additive_type_token_enum pptx_st_tlbehavior_additive_type_token_enum;
typedef enum pptx_st_tlbehavior_accumulate_type_token_enum pptx_st_tlbehavior_accumulate_type_token_enum;
typedef enum pptx_st_tlbehavior_transform_type_token_enum pptx_st_tlbehavior_transform_type_token_enum;
typedef enum pptx_st_tlbehavior_override_type_token_enum pptx_st_tlbehavior_override_type_token_enum;

typedef struct pptx_ct_p_tlcommon_behavior_data_s pptx_ct_p_tlcommon_behavior_data;
pptx_ct_p_tlcommon_behavior_data *pptx_ct_p_tlcommon_behavior_data_new(xmlNode *node);
void pptx_ct_p_tlcommon_behavior_data_free(pptx_ct_p_tlcommon_behavior_data *obj);
pptx_ct_p_tlcommon_time_node_data *pptx_ct_p_tlcommon_behavior_data_get_c_tn(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_ct_p_tltime_target_element *pptx_ct_p_tlcommon_behavior_data_get_tgt_el(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_ct_p_tlbehavior_attribute_name_list *pptx_ct_p_tlcommon_behavior_data_get_attr_name_lst(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_st_tlbehavior_additive_type_token_enum pptx_ct_p_tlcommon_behavior_data_get_additive(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_st_tlbehavior_accumulate_type_token_enum pptx_ct_p_tlcommon_behavior_data_get_accumulate(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_st_tlbehavior_transform_type_token_enum pptx_ct_p_tlcommon_behavior_data_get_xfrm_type(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_string pptx_ct_p_tlcommon_behavior_data_get_from(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_string pptx_ct_p_tlcommon_behavior_data_get_to(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_string pptx_ct_p_tlcommon_behavior_data_get_by(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_string pptx_ct_p_tlcommon_behavior_data_get_rctx(const pptx_ct_p_tlcommon_behavior_data *const obj);
pptx_st_tlbehavior_override_type_token_enum pptx_ct_p_tlcommon_behavior_data_get_override(const pptx_ct_p_tlcommon_behavior_data *const obj);
int32_t pptx_ct_p_tlcommon_behavior_data_get_index(pptx_ct_p_tlcommon_behavior_data *obj);

#endif /* __PPTX_CT_P_TLCOMMON_BEHAVIOR_DATA_H__ */
