#ifndef __PPTX_CT_A_EFFECT_CONTAINER_H__
#define __PPTX_CT_A_EFFECT_CONTAINER_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_effect_container_s pptx_ct_a_effect_container;
typedef struct pptx_ct_a_effect_reference_s pptx_ct_a_effect_reference;
typedef struct pptx_ct_a_alpha_bi_level_effect_s pptx_ct_a_alpha_bi_level_effect;
typedef struct pptx_ct_a_alpha_ceiling_effect_s pptx_ct_a_alpha_ceiling_effect;
typedef struct pptx_ct_a_alpha_floor_effect_s pptx_ct_a_alpha_floor_effect;
typedef struct pptx_ct_a_alpha_inverse_effect_s pptx_ct_a_alpha_inverse_effect;
typedef struct pptx_ct_a_alpha_modulate_effect_s pptx_ct_a_alpha_modulate_effect;
typedef struct pptx_ct_a_alpha_modulate_fixed_effect_s pptx_ct_a_alpha_modulate_fixed_effect;
typedef struct pptx_ct_a_alpha_outset_effect_s pptx_ct_a_alpha_outset_effect;
typedef struct pptx_ct_a_alpha_replace_effect_s pptx_ct_a_alpha_replace_effect;
typedef struct pptx_ct_a_bi_level_effect_s pptx_ct_a_bi_level_effect;
typedef struct pptx_ct_a_blend_effect_s pptx_ct_a_blend_effect;
typedef struct pptx_ct_a_blur_effect_s pptx_ct_a_blur_effect;
typedef struct pptx_ct_a_color_change_effect_s pptx_ct_a_color_change_effect;
typedef struct pptx_ct_a_color_replace_effect_s pptx_ct_a_color_replace_effect;
typedef struct pptx_ct_a_duotone_effect_s pptx_ct_a_duotone_effect;
typedef struct pptx_ct_a_fill_effect_s pptx_ct_a_fill_effect;
typedef struct pptx_ct_a_fill_overlay_effect_s pptx_ct_a_fill_overlay_effect;
typedef struct pptx_ct_a_glow_effect_s pptx_ct_a_glow_effect;
typedef struct pptx_ct_a_grayscale_effect_s pptx_ct_a_grayscale_effect;
typedef struct pptx_ct_a_hsleffect_s pptx_ct_a_hsleffect;
typedef struct pptx_ct_a_inner_shadow_effect_s pptx_ct_a_inner_shadow_effect;
typedef struct pptx_ct_a_luminance_effect_s pptx_ct_a_luminance_effect;
typedef struct pptx_ct_a_outer_shadow_effect_s pptx_ct_a_outer_shadow_effect;
typedef struct pptx_ct_a_preset_shadow_effect_s pptx_ct_a_preset_shadow_effect;
typedef struct pptx_ct_a_reflection_effect_s pptx_ct_a_reflection_effect;
typedef struct pptx_ct_a_relative_offset_effect_s pptx_ct_a_relative_offset_effect;
typedef struct pptx_ct_a_soft_edges_effect_s pptx_ct_a_soft_edges_effect;
typedef struct pptx_ct_a_tint_effect_s pptx_ct_a_tint_effect;
typedef struct pptx_ct_a_transform_effect_s pptx_ct_a_transform_effect;
typedef enum pptx_st_effect_container_type_token_enum pptx_st_effect_container_type_token_enum;

typedef struct pptx_ct_a_effect_container_s pptx_ct_a_effect_container;
pptx_ct_a_effect_container *pptx_ct_a_effect_container_new(xmlNode *node);
void pptx_ct_a_effect_container_free(pptx_ct_a_effect_container *obj);
pptx_ct_a_effect_container **pptx_ct_a_effect_container_get_effect_cont(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_effect_reference **pptx_ct_a_effect_container_get_effect_effect(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_bi_level_effect **pptx_ct_a_effect_container_get_effect_alpha_bi_level(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_ceiling_effect **pptx_ct_a_effect_container_get_effect_alpha_ceiling(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_floor_effect **pptx_ct_a_effect_container_get_effect_alpha_floor(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_inverse_effect **pptx_ct_a_effect_container_get_effect_alpha_inv(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_modulate_effect **pptx_ct_a_effect_container_get_effect_alpha_mod(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_modulate_fixed_effect **pptx_ct_a_effect_container_get_effect_alpha_mod_fix(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_outset_effect **pptx_ct_a_effect_container_get_effect_alpha_outset(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_alpha_replace_effect **pptx_ct_a_effect_container_get_effect_alpha_repl(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_bi_level_effect **pptx_ct_a_effect_container_get_effect_bi_level(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_blend_effect **pptx_ct_a_effect_container_get_effect_blend(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_blur_effect **pptx_ct_a_effect_container_get_effect_blur(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_color_change_effect **pptx_ct_a_effect_container_get_effect_clr_change(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_color_replace_effect **pptx_ct_a_effect_container_get_effect_clr_repl(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_duotone_effect **pptx_ct_a_effect_container_get_effect_duotone(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_fill_effect **pptx_ct_a_effect_container_get_effect_fill(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_fill_overlay_effect **pptx_ct_a_effect_container_get_effect_fill_overlay(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_glow_effect **pptx_ct_a_effect_container_get_effect_glow(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_grayscale_effect **pptx_ct_a_effect_container_get_effect_grayscl(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_hsleffect **pptx_ct_a_effect_container_get_effect_hsl(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_inner_shadow_effect **pptx_ct_a_effect_container_get_effect_inner_shdw(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_luminance_effect **pptx_ct_a_effect_container_get_effect_lum(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_outer_shadow_effect **pptx_ct_a_effect_container_get_effect_outer_shdw(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_preset_shadow_effect **pptx_ct_a_effect_container_get_effect_prst_shdw(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_reflection_effect **pptx_ct_a_effect_container_get_effect_reflection(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_relative_offset_effect **pptx_ct_a_effect_container_get_effect_rel_off(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_soft_edges_effect **pptx_ct_a_effect_container_get_effect_soft_edge(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_tint_effect **pptx_ct_a_effect_container_get_effect_tint(const pptx_ct_a_effect_container *const obj);
pptx_ct_a_transform_effect **pptx_ct_a_effect_container_get_effect_xfrm(const pptx_ct_a_effect_container *const obj);
pptx_st_effect_container_type_token_enum pptx_ct_a_effect_container_get_type(const pptx_ct_a_effect_container *const obj);
pptx_string pptx_ct_a_effect_container_get_name(const pptx_ct_a_effect_container *const obj);
int32_t pptx_ct_a_effect_container_get_index(pptx_ct_a_effect_container *obj);

#endif /* __PPTX_CT_A_EFFECT_CONTAINER_H__ */
