#ifndef __PPTX_ST_PRESET_CAMERA_TYPE_H__
#define __PPTX_ST_PRESET_CAMERA_TYPE_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef enum pptx_st_preset_camera_type_token_enum {
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_TOP_UP,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS2_LEFT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_LEFT,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_TOP_LEFT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS1_TOP,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_BOTTOM_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS4_LEFT,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_FRONT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_CONTRASTING_LEFT_FACING,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_RELAXED,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_LEFT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS4_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_RIGHT_UP,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_LEFT,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_TOP_LEFT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_ABOVE_LEFT_FACING,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_TOP_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_TOP_DOWN,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_BOTTOM,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS4_BOTTOM,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_RELAXED_MODERATELY,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_HEROIC_EXTREME_RIGHT_FACING,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_TOP_RIGHT,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_LEFT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS2_TOP,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_BOTTOM_DOWN,
    ST_PRESET_CAMERA_TYPE_ORTHOGRAPHIC_FRONT,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_BOTTOM,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS3_LEFT,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_BOTTOM_RIGHT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_ABOVE_RIGHT_FACING,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_BOTTOM_LEFT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_HEROIC_EXTREME_LEFT_FACING,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_LEFT_UP,
    ST_PRESET_CAMERA_TYPE_NIL,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_RIGHT_DOWN,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_ABOVE,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_RIGHT,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_TOP_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS1_LEFT,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_BOTTOM_UP,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS2_RIGHT,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_BOTTOM_LEFT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_FRONT,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_TOP,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_LEFT_DOWN,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_TOP,
    ST_PRESET_CAMERA_TYPE_LEGACY_PERSPECTIVE_RIGHT,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_FRONT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_CONTRASTING_RIGHT_FACING,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_BOTTOM,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_HEROIC_LEFT_FACING,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_BOTTOM_RIGHT,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_BOTTOM_LEFT,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_BELOW,
    ST_PRESET_CAMERA_TYPE_OBLIQUE_TOP_LEFT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS3_BOTTOM,
    ST_PRESET_CAMERA_TYPE_PERSPECTIVE_HEROIC_RIGHT_FACING,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS3_RIGHT,
    ST_PRESET_CAMERA_TYPE_ISOMETRIC_OFF_AXIS1_RIGHT,
    ST_PRESET_CAMERA_TYPE_LEGACY_OBLIQUE_TOP
} pptx_st_preset_camera_type_token_enum;

pptx_st_preset_camera_type_token_enum pptx_get_st_preset_camera_type(xmlNode *node, const xmlChar *property);

#endif /* __PPTX_ST_PRESET_CAMERA_TYPE_H__ */
