#ifndef __PPTX_CT_DGM_DIAGRAM_DEFINITION_H__
#define __PPTX_CT_DGM_DIAGRAM_DEFINITION_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_dgm_name_s pptx_ct_dgm_name;
typedef struct pptx_ct_dgm_description_s pptx_ct_dgm_description;
typedef struct pptx_ct_dgm_categories_s pptx_ct_dgm_categories;
typedef struct pptx_ct_dgm_sample_data_s pptx_ct_dgm_sample_data;
typedef struct pptx_ct_dgm_layout_node_s pptx_ct_dgm_layout_node;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;

typedef struct pptx_ct_dgm_diagram_definition_s pptx_ct_dgm_diagram_definition;
pptx_ct_dgm_diagram_definition *pptx_ct_dgm_diagram_definition_new(xmlNode *node);
void pptx_ct_dgm_diagram_definition_free(pptx_ct_dgm_diagram_definition *obj);
pptx_ct_dgm_name **pptx_ct_dgm_diagram_definition_get_title(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_dgm_description **pptx_ct_dgm_diagram_definition_get_desc(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_dgm_categories *pptx_ct_dgm_diagram_definition_get_cat_lst(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_dgm_sample_data *pptx_ct_dgm_diagram_definition_get_samp_data(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_dgm_sample_data *pptx_ct_dgm_diagram_definition_get_style_data(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_dgm_sample_data *pptx_ct_dgm_diagram_definition_get_clr_data(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_dgm_layout_node *pptx_ct_dgm_diagram_definition_get_layout_node(const pptx_ct_dgm_diagram_definition *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_dgm_diagram_definition_get_ext_lst(const pptx_ct_dgm_diagram_definition *const obj);
pptx_string pptx_ct_dgm_diagram_definition_get_unique_id(const pptx_ct_dgm_diagram_definition *const obj);
pptx_string pptx_ct_dgm_diagram_definition_get_min_ver(const pptx_ct_dgm_diagram_definition *const obj);
pptx_string pptx_ct_dgm_diagram_definition_get_def_style(const pptx_ct_dgm_diagram_definition *const obj);
int32_t pptx_ct_dgm_diagram_definition_get_index(pptx_ct_dgm_diagram_definition *obj);

#endif /* __PPTX_CT_DGM_DIAGRAM_DEFINITION_H__ */
