#ifndef __PPTX_ST_TEXT_SHAPE_TYPE_H__
#define __PPTX_ST_TEXT_SHAPE_TYPE_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef enum pptx_st_text_shape_type_token_enum {
    ST_TEXT_SHAPE_TYPE_TEXT_DEFLATE_INFLATE_DEFLATE,
    ST_TEXT_SHAPE_TYPE_TEXT_CASCADE_UP,
    ST_TEXT_SHAPE_TYPE_TEXT_CIRCLE_POUR,
    ST_TEXT_SHAPE_TYPE_TEXT_CURVE_DOWN,
    ST_TEXT_SHAPE_TYPE_TEXT_FADE_DOWN,
    ST_TEXT_SHAPE_TYPE_TEXT_CIRCLE,
    ST_TEXT_SHAPE_TYPE_TEXT_NO_SHAPE,
    ST_TEXT_SHAPE_TYPE_TEXT_WAVE4,
    ST_TEXT_SHAPE_TYPE_TEXT_WAVE2,
    ST_TEXT_SHAPE_TYPE_TEXT_WAVE1,
    ST_TEXT_SHAPE_TYPE_TEXT_ARCH_DOWN,
    ST_TEXT_SHAPE_TYPE_TEXT_INFLATE_BOTTOM,
    ST_TEXT_SHAPE_TYPE_TEXT_ARCH_DOWN_POUR,
    ST_TEXT_SHAPE_TYPE_TEXT_CURVE_UP,
    ST_TEXT_SHAPE_TYPE_TEXT_FADE_UP,
    ST_TEXT_SHAPE_TYPE_TEXT_SLANT_UP,
    ST_TEXT_SHAPE_TYPE_TEXT_FADE_LEFT,
    ST_TEXT_SHAPE_TYPE_TEXT_DEFLATE_TOP,
    ST_TEXT_SHAPE_TYPE_TEXT_TRIANGLE,
    ST_TEXT_SHAPE_TYPE_TEXT_FADE_RIGHT,
    ST_TEXT_SHAPE_TYPE_TEXT_CASCADE_DOWN,
    ST_TEXT_SHAPE_TYPE_TEXT_ARCH_UP,
    ST_TEXT_SHAPE_TYPE_TEXT_BUTTON_POUR,
    ST_TEXT_SHAPE_TYPE_TEXT_CAN_DOWN,
    ST_TEXT_SHAPE_TYPE_TEXT_RING_OUTSIDE,
    ST_TEXT_SHAPE_TYPE_TEXT_TRIANGLE_INVERTED,
    ST_TEXT_SHAPE_TYPE_TEXT_RING_INSIDE,
    ST_TEXT_SHAPE_TYPE_TEXT_BUTTON,
    ST_TEXT_SHAPE_TYPE_TEXT_DEFLATE_INFLATE,
    ST_TEXT_SHAPE_TYPE_TEXT_CAN_UP,
    ST_TEXT_SHAPE_TYPE_TEXT_CHEVRON,
    ST_TEXT_SHAPE_TYPE_TEXT_INFLATE_TOP,
    ST_TEXT_SHAPE_TYPE_TEXT_INFLATE,
    ST_TEXT_SHAPE_TYPE_TEXT_DEFLATE_BOTTOM,
    ST_TEXT_SHAPE_TYPE_TEXT_DOUBLE_WAVE1,
    ST_TEXT_SHAPE_TYPE_NIL,
    ST_TEXT_SHAPE_TYPE_TEXT_SLANT_DOWN,
    ST_TEXT_SHAPE_TYPE_TEXT_STOP,
    ST_TEXT_SHAPE_TYPE_TEXT_CHEVRON_INVERTED,
    ST_TEXT_SHAPE_TYPE_TEXT_PLAIN,
    ST_TEXT_SHAPE_TYPE_TEXT_ARCH_UP_POUR,
    ST_TEXT_SHAPE_TYPE_TEXT_DEFLATE
} pptx_st_text_shape_type_token_enum;

pptx_st_text_shape_type_token_enum pptx_get_st_text_shape_type(xmlNode *node, const xmlChar *property);

#endif /* __PPTX_ST_TEXT_SHAPE_TYPE_H__ */
