#ifndef __PPTX_CT_A_TEXT_CHARACTER_PROPERTIES_H__
#define __PPTX_CT_A_TEXT_CHARACTER_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_line_properties_s pptx_ct_a_line_properties;
typedef struct pptx_ct_a_no_fill_properties_s pptx_ct_a_no_fill_properties;
typedef struct pptx_ct_a_solid_color_fill_properties_s pptx_ct_a_solid_color_fill_properties;
typedef struct pptx_ct_a_gradient_fill_properties_s pptx_ct_a_gradient_fill_properties;
typedef struct pptx_ct_a_blip_fill_properties_s pptx_ct_a_blip_fill_properties;
typedef struct pptx_ct_a_pattern_fill_properties_s pptx_ct_a_pattern_fill_properties;
typedef struct pptx_ct_a_group_fill_properties_s pptx_ct_a_group_fill_properties;
typedef struct pptx_ct_a_effect_list_s pptx_ct_a_effect_list;
typedef struct pptx_ct_a_effect_container_s pptx_ct_a_effect_container;
typedef struct pptx_ct_a_color_s pptx_ct_a_color;
typedef struct pptx_ct_a_text_underline_line_follow_text_s pptx_ct_a_text_underline_line_follow_text;
typedef struct pptx_ct_a_text_underline_fill_follow_text_s pptx_ct_a_text_underline_fill_follow_text;
typedef struct pptx_ct_a_text_underline_fill_group_wrapper_s pptx_ct_a_text_underline_fill_group_wrapper;
typedef struct pptx_ct_a_text_font_s pptx_ct_a_text_font;
typedef struct pptx_ct_a_hyperlink_s pptx_ct_a_hyperlink;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;
typedef enum pptx_st_text_underline_type_token_enum pptx_st_text_underline_type_token_enum;
typedef enum pptx_st_text_strike_type_token_enum pptx_st_text_strike_type_token_enum;
typedef enum pptx_st_text_caps_type_token_enum pptx_st_text_caps_type_token_enum;

typedef struct pptx_ct_a_text_character_properties_s pptx_ct_a_text_character_properties;
pptx_ct_a_text_character_properties *pptx_ct_a_text_character_properties_new(xmlNode *node);
void pptx_ct_a_text_character_properties_free(pptx_ct_a_text_character_properties *obj);
pptx_ct_a_line_properties *pptx_ct_a_text_character_properties_get_ln(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_no_fill_properties *pptx_ct_a_text_character_properties_get_fill_properties_no_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_solid_color_fill_properties *pptx_ct_a_text_character_properties_get_fill_properties_solid_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_gradient_fill_properties *pptx_ct_a_text_character_properties_get_fill_properties_grad_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_blip_fill_properties *pptx_ct_a_text_character_properties_get_fill_properties_blip_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_pattern_fill_properties *pptx_ct_a_text_character_properties_get_fill_properties_patt_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_group_fill_properties *pptx_ct_a_text_character_properties_get_fill_properties_grp_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_effect_list *pptx_ct_a_text_character_properties_get_effect_properties_effect_lst(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_effect_container *pptx_ct_a_text_character_properties_get_effect_properties_effect_dag(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_color *pptx_ct_a_text_character_properties_get_highlight(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_underline_line_follow_text *pptx_ct_a_text_character_properties_get_text_underline_line_u_ln_tx(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_line_properties *pptx_ct_a_text_character_properties_get_text_underline_line_u_ln(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_underline_fill_follow_text *pptx_ct_a_text_character_properties_get_text_underline_fill_u_fill_tx(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_underline_fill_group_wrapper *pptx_ct_a_text_character_properties_get_text_underline_fill_u_fill(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_font *pptx_ct_a_text_character_properties_get_latin(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_font *pptx_ct_a_text_character_properties_get_ea(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_font *pptx_ct_a_text_character_properties_get_cs(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_text_font *pptx_ct_a_text_character_properties_get_sym(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_hyperlink *pptx_ct_a_text_character_properties_get_hlink_click(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_hyperlink *pptx_ct_a_text_character_properties_get_hlink_mouse_over(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_rtl(const pptx_ct_a_text_character_properties *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_text_character_properties_get_ext_lst(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_kumimoji(const pptx_ct_a_text_character_properties *const obj);
pptx_string pptx_ct_a_text_character_properties_get_lang(const pptx_ct_a_text_character_properties *const obj);
pptx_string pptx_ct_a_text_character_properties_get_alt_lang(const pptx_ct_a_text_character_properties *const obj);
pptx_int pptx_ct_a_text_character_properties_get_sz(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_b(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_i(const pptx_ct_a_text_character_properties *const obj);
pptx_st_text_underline_type_token_enum pptx_ct_a_text_character_properties_get_u(const pptx_ct_a_text_character_properties *const obj);
pptx_st_text_strike_type_token_enum pptx_ct_a_text_character_properties_get_strike(const pptx_ct_a_text_character_properties *const obj);
pptx_int pptx_ct_a_text_character_properties_get_kern(const pptx_ct_a_text_character_properties *const obj);
pptx_st_text_caps_type_token_enum pptx_ct_a_text_character_properties_get_cap(const pptx_ct_a_text_character_properties *const obj);
pptx_string pptx_ct_a_text_character_properties_get_spc(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_normalize_h(const pptx_ct_a_text_character_properties *const obj);
pptx_string pptx_ct_a_text_character_properties_get_baseline(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_no_proof(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_dirty(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_err(const pptx_ct_a_text_character_properties *const obj);
pptx_bool pptx_ct_a_text_character_properties_get_smt_clean(const pptx_ct_a_text_character_properties *const obj);
pptx_uint pptx_ct_a_text_character_properties_get_smt_id(const pptx_ct_a_text_character_properties *const obj);
pptx_string pptx_ct_a_text_character_properties_get_bmk(const pptx_ct_a_text_character_properties *const obj);
int32_t pptx_ct_a_text_character_properties_get_index(pptx_ct_a_text_character_properties *obj);

#endif /* __PPTX_CT_A_TEXT_CHARACTER_PROPERTIES_H__ */
