#ifndef __PPTX_ST_CONSTRAINT_TYPE_H__
#define __PPTX_ST_CONSTRAINT_TYPE_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef enum pptx_st_constraint_type_token_enum {
    ST_CONSTRAINT_TYPE_CTR_YOFF,
    ST_CONSTRAINT_TYPE_SP,
    ST_CONSTRAINT_TYPE_R_MARG,
    ST_CONSTRAINT_TYPE_W_AR_H,
    ST_CONSTRAINT_TYPE_H_AR_H,
    ST_CONSTRAINT_TYPE_USER_H,
    ST_CONSTRAINT_TYPE_ALIGN_OFF,
    ST_CONSTRAINT_TYPE_B_MARG,
    ST_CONSTRAINT_TYPE_DIAM,
    ST_CONSTRAINT_TYPE_USER_I,
    ST_CONSTRAINT_TYPE_CTR_XOFF,
    ST_CONSTRAINT_TYPE_BEG_MARG,
    ST_CONSTRAINT_TYPE_T_MARG,
    ST_CONSTRAINT_TYPE_BEG_PAD,
    ST_CONSTRAINT_TYPE_CTR_Y,
    ST_CONSTRAINT_TYPE_CTR_X,
    ST_CONSTRAINT_TYPE_L_OFF,
    ST_CONSTRAINT_TYPE_BEND_DIST,
    ST_CONSTRAINT_TYPE_PRIM_FONT_SZ,
    ST_CONSTRAINT_TYPE_T,
    ST_CONSTRAINT_TYPE_USER_M,
    ST_CONSTRAINT_TYPE_W,
    ST_CONSTRAINT_TYPE_NIL,
    ST_CONSTRAINT_TYPE_END_PAD,
    ST_CONSTRAINT_TYPE_STEM_THICK,
    ST_CONSTRAINT_TYPE_USER_T,
    ST_CONSTRAINT_TYPE_W_OFF,
    ST_CONSTRAINT_TYPE_USER_U,
    ST_CONSTRAINT_TYPE_SEC_SIB_SP,
    ST_CONSTRAINT_TYPE_PYRA_ACCT_RATIO,
    ST_CONSTRAINT_TYPE_USER_E,
    ST_CONSTRAINT_TYPE_END_MARG,
    ST_CONSTRAINT_TYPE_USER_L,
    ST_CONSTRAINT_TYPE_USER_S,
    ST_CONSTRAINT_TYPE_USER_V,
    ST_CONSTRAINT_TYPE_USER_W,
    ST_CONSTRAINT_TYPE_NONE,
    ST_CONSTRAINT_TYPE_B,
    ST_CONSTRAINT_TYPE_USER_R,
    ST_CONSTRAINT_TYPE_R_OFF,
    ST_CONSTRAINT_TYPE_USER_P,
    ST_CONSTRAINT_TYPE_USER_Q,
    ST_CONSTRAINT_TYPE_H,
    ST_CONSTRAINT_TYPE_SEC_FONT_SZ,
    ST_CONSTRAINT_TYPE_H_OFF,
    ST_CONSTRAINT_TYPE_USER_Z,
    ST_CONSTRAINT_TYPE_L,
    ST_CONSTRAINT_TYPE_USER_X,
    ST_CONSTRAINT_TYPE_USER_Y,
    ST_CONSTRAINT_TYPE_USER_F,
    ST_CONSTRAINT_TYPE_USER_G,
    ST_CONSTRAINT_TYPE_USER_D,
    ST_CONSTRAINT_TYPE_R,
    ST_CONSTRAINT_TYPE_USER_B,
    ST_CONSTRAINT_TYPE_B_OFF,
    ST_CONSTRAINT_TYPE_L_MARG,
    ST_CONSTRAINT_TYPE_USER_A,
    ST_CONSTRAINT_TYPE_USER_N,
    ST_CONSTRAINT_TYPE_USER_O,
    ST_CONSTRAINT_TYPE_SIB_SP,
    ST_CONSTRAINT_TYPE_USER_C,
    ST_CONSTRAINT_TYPE_USER_J,
    ST_CONSTRAINT_TYPE_USER_K,
    ST_CONSTRAINT_TYPE_CONN_DIST,
    ST_CONSTRAINT_TYPE_T_OFF
} pptx_st_constraint_type_token_enum;

pptx_st_constraint_type_token_enum pptx_get_st_constraint_type(xmlNode *node, const xmlChar *property);

#endif /* __PPTX_ST_CONSTRAINT_TYPE_H__ */
