#ifndef __PPTX_CT_A_TABLE_CELL_PROPERTIES_H__
#define __PPTX_CT_A_TABLE_CELL_PROPERTIES_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_line_properties_s pptx_ct_a_line_properties;
typedef struct pptx_ct_a_cell_3d_s pptx_ct_a_cell_3d;
typedef struct pptx_ct_a_no_fill_properties_s pptx_ct_a_no_fill_properties;
typedef struct pptx_ct_a_solid_color_fill_properties_s pptx_ct_a_solid_color_fill_properties;
typedef struct pptx_ct_a_gradient_fill_properties_s pptx_ct_a_gradient_fill_properties;
typedef struct pptx_ct_a_blip_fill_properties_s pptx_ct_a_blip_fill_properties;
typedef struct pptx_ct_a_pattern_fill_properties_s pptx_ct_a_pattern_fill_properties;
typedef struct pptx_ct_a_group_fill_properties_s pptx_ct_a_group_fill_properties;
typedef struct pptx_ct_a_headers_s pptx_ct_a_headers;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;
typedef enum pptx_st_text_vertical_type_token_enum pptx_st_text_vertical_type_token_enum;
typedef enum pptx_st_text_anchoring_type_token_enum pptx_st_text_anchoring_type_token_enum;
typedef enum pptx_st_text_horz_overflow_type_token_enum pptx_st_text_horz_overflow_type_token_enum;

typedef struct pptx_ct_a_table_cell_properties_s pptx_ct_a_table_cell_properties;
pptx_ct_a_table_cell_properties *pptx_ct_a_table_cell_properties_new(xmlNode *node);
void pptx_ct_a_table_cell_properties_free(pptx_ct_a_table_cell_properties *obj);
pptx_ct_a_line_properties *pptx_ct_a_table_cell_properties_get_ln_l(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_line_properties *pptx_ct_a_table_cell_properties_get_ln_r(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_line_properties *pptx_ct_a_table_cell_properties_get_ln_t(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_line_properties *pptx_ct_a_table_cell_properties_get_ln_b(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_line_properties *pptx_ct_a_table_cell_properties_get_ln_tl_to_br(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_line_properties *pptx_ct_a_table_cell_properties_get_ln_bl_to_tr(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_cell_3d *pptx_ct_a_table_cell_properties_get_cell_3d(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_no_fill_properties *pptx_ct_a_table_cell_properties_get_fill_properties_no_fill(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_solid_color_fill_properties *pptx_ct_a_table_cell_properties_get_fill_properties_solid_fill(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_gradient_fill_properties *pptx_ct_a_table_cell_properties_get_fill_properties_grad_fill(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_blip_fill_properties *pptx_ct_a_table_cell_properties_get_fill_properties_blip_fill(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_pattern_fill_properties *pptx_ct_a_table_cell_properties_get_fill_properties_patt_fill(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_group_fill_properties *pptx_ct_a_table_cell_properties_get_fill_properties_grp_fill(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_headers *pptx_ct_a_table_cell_properties_get_headers(const pptx_ct_a_table_cell_properties *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_table_cell_properties_get_ext_lst(const pptx_ct_a_table_cell_properties *const obj);
pptx_string pptx_ct_a_table_cell_properties_get_mar_l(const pptx_ct_a_table_cell_properties *const obj);
pptx_string pptx_ct_a_table_cell_properties_get_mar_r(const pptx_ct_a_table_cell_properties *const obj);
pptx_string pptx_ct_a_table_cell_properties_get_mar_t(const pptx_ct_a_table_cell_properties *const obj);
pptx_string pptx_ct_a_table_cell_properties_get_mar_b(const pptx_ct_a_table_cell_properties *const obj);
pptx_st_text_vertical_type_token_enum pptx_ct_a_table_cell_properties_get_vert(const pptx_ct_a_table_cell_properties *const obj);
pptx_st_text_anchoring_type_token_enum pptx_ct_a_table_cell_properties_get_anchor(const pptx_ct_a_table_cell_properties *const obj);
pptx_bool pptx_ct_a_table_cell_properties_get_anchor_ctr(const pptx_ct_a_table_cell_properties *const obj);
pptx_st_text_horz_overflow_type_token_enum pptx_ct_a_table_cell_properties_get_horz_overflow(const pptx_ct_a_table_cell_properties *const obj);
int32_t pptx_ct_a_table_cell_properties_get_index(pptx_ct_a_table_cell_properties *obj);

#endif /* __PPTX_CT_A_TABLE_CELL_PROPERTIES_H__ */
