#ifndef __PPTX_CT_A_TEXT_UNDERLINE_FILL_GROUP_WRAPPER_H__
#define __PPTX_CT_A_TEXT_UNDERLINE_FILL_GROUP_WRAPPER_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_no_fill_properties_s pptx_ct_a_no_fill_properties;
typedef struct pptx_ct_a_solid_color_fill_properties_s pptx_ct_a_solid_color_fill_properties;
typedef struct pptx_ct_a_gradient_fill_properties_s pptx_ct_a_gradient_fill_properties;
typedef struct pptx_ct_a_blip_fill_properties_s pptx_ct_a_blip_fill_properties;
typedef struct pptx_ct_a_pattern_fill_properties_s pptx_ct_a_pattern_fill_properties;
typedef struct pptx_ct_a_group_fill_properties_s pptx_ct_a_group_fill_properties;

typedef struct pptx_ct_a_text_underline_fill_group_wrapper_s pptx_ct_a_text_underline_fill_group_wrapper;
pptx_ct_a_text_underline_fill_group_wrapper *pptx_ct_a_text_underline_fill_group_wrapper_new(xmlNode *node);
void pptx_ct_a_text_underline_fill_group_wrapper_free(pptx_ct_a_text_underline_fill_group_wrapper *obj);
pptx_ct_a_no_fill_properties *pptx_ct_a_text_underline_fill_group_wrapper_get_fill_properties_no_fill(const pptx_ct_a_text_underline_fill_group_wrapper *const obj);
pptx_ct_a_solid_color_fill_properties *pptx_ct_a_text_underline_fill_group_wrapper_get_fill_properties_solid_fill(const pptx_ct_a_text_underline_fill_group_wrapper *const obj);
pptx_ct_a_gradient_fill_properties *pptx_ct_a_text_underline_fill_group_wrapper_get_fill_properties_grad_fill(const pptx_ct_a_text_underline_fill_group_wrapper *const obj);
pptx_ct_a_blip_fill_properties *pptx_ct_a_text_underline_fill_group_wrapper_get_fill_properties_blip_fill(const pptx_ct_a_text_underline_fill_group_wrapper *const obj);
pptx_ct_a_pattern_fill_properties *pptx_ct_a_text_underline_fill_group_wrapper_get_fill_properties_patt_fill(const pptx_ct_a_text_underline_fill_group_wrapper *const obj);
pptx_ct_a_group_fill_properties *pptx_ct_a_text_underline_fill_group_wrapper_get_fill_properties_grp_fill(const pptx_ct_a_text_underline_fill_group_wrapper *const obj);
int32_t pptx_ct_a_text_underline_fill_group_wrapper_get_index(pptx_ct_a_text_underline_fill_group_wrapper *obj);

#endif /* __PPTX_CT_A_TEXT_UNDERLINE_FILL_GROUP_WRAPPER_H__ */
