#ifndef __PPTX_CT_A_TABLE_STYLE_CELL_STYLE_H__
#define __PPTX_CT_A_TABLE_STYLE_CELL_STYLE_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_table_cell_border_style_s pptx_ct_a_table_cell_border_style;
typedef struct pptx_ct_a_fill_properties_s pptx_ct_a_fill_properties;
typedef struct pptx_ct_a_style_matrix_reference_s pptx_ct_a_style_matrix_reference;
typedef struct pptx_ct_a_cell_3d_s pptx_ct_a_cell_3d;

typedef struct pptx_ct_a_table_style_cell_style_s pptx_ct_a_table_style_cell_style;
pptx_ct_a_table_style_cell_style *pptx_ct_a_table_style_cell_style_new(xmlNode *node);
void pptx_ct_a_table_style_cell_style_free(pptx_ct_a_table_style_cell_style *obj);
pptx_ct_a_table_cell_border_style *pptx_ct_a_table_style_cell_style_get_tc_bdr(const pptx_ct_a_table_style_cell_style *const obj);
pptx_ct_a_fill_properties *pptx_ct_a_table_style_cell_style_get_themeable_fill_style_fill(const pptx_ct_a_table_style_cell_style *const obj);
pptx_ct_a_style_matrix_reference *pptx_ct_a_table_style_cell_style_get_themeable_fill_style_fill_ref(const pptx_ct_a_table_style_cell_style *const obj);
pptx_ct_a_cell_3d *pptx_ct_a_table_style_cell_style_get_cell_3d(const pptx_ct_a_table_style_cell_style *const obj);
int32_t pptx_ct_a_table_style_cell_style_get_index(pptx_ct_a_table_style_cell_style *obj);

#endif /* __PPTX_CT_A_TABLE_STYLE_CELL_STYLE_H__ */
