#ifndef __PPTX_CT_A_GVML_GRAPHICAL_OBJECT_FRAME_H__
#define __PPTX_CT_A_GVML_GRAPHICAL_OBJECT_FRAME_H__

#ifndef __PPTX_PRIVATE_INCLUDES__
#error "Please do not include this file directly"
#endif /* __PPTX_H__ */

#include <libxml/parser.h>
#include <private/pptx-common.h>

typedef struct pptx_ct_a_gvml_graphic_frame_non_visual_s pptx_ct_a_gvml_graphic_frame_non_visual;
typedef struct pptx_ct_a_graphical_object_s pptx_ct_a_graphical_object;
typedef struct pptx_ct_a_transform_2d_s pptx_ct_a_transform_2d;
typedef struct pptx_ct_a_office_art_extension_list_s pptx_ct_a_office_art_extension_list;

typedef struct pptx_ct_a_gvml_graphical_object_frame_s pptx_ct_a_gvml_graphical_object_frame;
pptx_ct_a_gvml_graphical_object_frame *pptx_ct_a_gvml_graphical_object_frame_new(xmlNode *node);
void pptx_ct_a_gvml_graphical_object_frame_free(pptx_ct_a_gvml_graphical_object_frame *obj);
pptx_ct_a_gvml_graphic_frame_non_visual *pptx_ct_a_gvml_graphical_object_frame_get_nv_graphic_frame_pr(const pptx_ct_a_gvml_graphical_object_frame *const obj);
pptx_ct_a_graphical_object *pptx_ct_a_gvml_graphical_object_frame_get_graphic(const pptx_ct_a_gvml_graphical_object_frame *const obj);
pptx_ct_a_transform_2d *pptx_ct_a_gvml_graphical_object_frame_get_xfrm(const pptx_ct_a_gvml_graphical_object_frame *const obj);
pptx_ct_a_office_art_extension_list *pptx_ct_a_gvml_graphical_object_frame_get_ext_lst(const pptx_ct_a_gvml_graphical_object_frame *const obj);
int32_t pptx_ct_a_gvml_graphical_object_frame_get_index(pptx_ct_a_gvml_graphical_object_frame *obj);

#endif /* __PPTX_CT_A_GVML_GRAPHICAL_OBJECT_FRAME_H__ */
