#ifdef __PPTX_PRIVATE_INCLUDES__ /* Include prevention */
#error "Please do not break this rule, it helps you prevent a mess"
#endif /* __PPTX_PRIVATE_INCLUDES__ */

#define __PPTX_PRIVATE_INCLUDES__ /* Allow private includes */

#ifndef __PPTX_H__
#define __PPTX_H__

#include <private/pptx-common.h>
#include <private/pptx-st-cross-between.h>
#include <private/pptx-st-constraint-type.h>
#include <private/pptx-st-tlanimate-color-space.h>
#include <private/pptx-st-path-fill-mode.h>
#include <private/pptx-st-preset-material-type.h>
#include <private/pptx-st-true-false.h>
#include <private/pptx-st-built-in-unit.h>
#include <private/pptx-st-transition-in-out-direction-type.h>
#include <private/pptx-st-yalign.h>
#include <private/pptx-st-text-horz-overflow-type.h>
#include <private/pptx-st-auto-text-rotation.h>
#include <private/pptx-st-alg-class.h>
#include <private/pptx-st-lbl-algn.h>
#include <private/pptx-st-continue-direction.h>
#include <private/pptx-st-bend-point.h>
#include <private/pptx-st-color-scheme-index.h>
#include <private/pptx-st-resize-handles-str.h>
#include <private/pptx-st-text-autonumber-scheme.h>
#include <private/pptx-st-tick-mark.h>
#include <private/pptx-st-iterate-type.h>
#include <private/pptx-st-tlprevious-action-type.h>
#include <private/pptx-st-tlpara-build-type.h>
#include <private/pptx-st-pen-alignment.h>
#include <private/pptx-st-text-tab-align-type.h>
#include <private/pptx-st-shape.h>
#include <private/pptx-st-size-represents.h>
#include <private/pptx-st-radar-style.h>
#include <private/pptx-st-text-strike-type.h>
#include <private/pptx-st-photo-album-frame-shape.h>
#include <private/pptx-st-tltime-node-master-relation.h>
#include <private/pptx-st-tltime-node-preset-class-type.h>
#include <private/pptx-st-print-what.h>
#include <private/pptx-st-blend-mode.h>
#include <private/pptx-st-web-color-type.h>
#include <private/pptx-st-breakpoint.h>
#include <private/pptx-st-crypt-prov.h>
#include <private/pptx-st-font-collection-index.h>
#include <private/pptx-st-bar-dir.h>
#include <private/pptx-st-line-cap.h>
#include <private/pptx-st-ax-pos.h>
#include <private/pptx-st-effect-container-type.h>
#include <private/pptx-st-secondary-child-alignment.h>
#include <private/pptx-st-preset-line-dash-val.h>
#include <private/pptx-st-tlbehavior-transform-type.h>
#include <private/pptx-st-ole-object-follow-color-scheme.h>
#include <private/pptx-st-constraint-relationship.h>
#include <private/pptx-st-child-direction.h>
#include <private/pptx-st-err-dir.h>
#include <private/pptx-st-tltime-node-fill-type.h>
#include <private/pptx-st-time-unit.h>
#include <private/pptx-st-vertical-alignment.h>
#include <private/pptx-st-connector-routing.h>
#include <private/pptx-st-xalign.h>
#include <private/pptx-st-conformance-class.h>
#include <private/pptx-st-transition-side-direction-type.h>
#include <private/pptx-st-pyramid-accent-text-margin.h>
#include <private/pptx-st-child-alignment.h>
#include <private/pptx-st-path-shade-type.h>
#include <private/pptx-st-axis-type.h>
#include <private/pptx-st-text-font-align-type.h>
#include <private/pptx-st-element-type.h>
#include <private/pptx-st-rotation-path.h>
#include <private/pptx-st-pt-type.h>
#include <private/pptx-st-light-rig-direction.h>
#include <private/pptx-st-line-end-type.h>
#include <private/pptx-st-pyramid-accent-position.h>
#include <private/pptx-st-text-block-direction.h>
#include <private/pptx-st-err-bar-type.h>
#include <private/pptx-st-parameter-id.h>
#include <private/pptx-st-system-color-val.h>
#include <private/pptx-st-orientation.h>
#include <private/pptx-st-dgm-build-step.h>
#include <private/pptx-st-offset.h>
#include <private/pptx-st-direction.h>
#include <private/pptx-st-grow-direction.h>
#include <private/pptx-st-child-order-type.h>
#include <private/pptx-st-center-shape-mapping.h>
#include <private/pptx-st-tlanimate-behavior-calc-mode.h>
#include <private/pptx-st-flow-direction.h>
#include <private/pptx-st-tlchart-subelement-type.h>
#include <private/pptx-st-connector-point.h>
#include <private/pptx-st-text-align-type.h>
#include <private/pptx-st-fallback-dimension.h>
#include <private/pptx-st-tltime-indefinite.h>
#include <private/pptx-st-text-anchoring-type.h>
#include <private/pptx-st-trendline-type.h>
#include <private/pptx-st-animation-chart-only-build-type.h>
#include <private/pptx-st-text-direction.h>
#include <private/pptx-st-line-end-length.h>
#include <private/pptx-st-text-underline-type.h>
#include <private/pptx-st-layout-mode.h>
#include <private/pptx-st-clr-app-method.h>
#include <private/pptx-st-tlnext-action-type.h>
#include <private/pptx-st-secondary-linear-direction.h>
#include <private/pptx-st-tlanimate-motion-behavior-origin.h>
#include <private/pptx-st-chart-build-step.h>
#include <private/pptx-st-animation-build-type.h>
#include <private/pptx-st-bevel-preset-type.h>
#include <private/pptx-st-starting-element.h>
#include <private/pptx-st-split-type.h>
#include <private/pptx-st-alg-type.h>
#include <private/pptx-st-text-anchor-horizontal.h>
#include <private/pptx-st-linear-direction.h>
#include <private/pptx-st-on-off1.h>
#include <private/pptx-st-text-wrapping-type.h>
#include <private/pptx-st-diagram-text-alignment.h>
#include <private/pptx-st-hierarchy-alignment.h>
#include <private/pptx-st-tlanimate-behavior-value-type.h>
#include <private/pptx-st-picture-format.h>
#include <private/pptx-st-web-screen-size.h>
#include <private/pptx-st-layout-target.h>
#include <private/pptx-st-black-white-mode.h>
#include <private/pptx-st-preset-shadow-val.h>
#include <private/pptx-st-tltrigger-runtime-node.h>
#include <private/pptx-st-tick-lbl-pos.h>
#include <private/pptx-st-tlanimate-effect-transition.h>
#include <private/pptx-st-compound-line.h>
#include <private/pptx-st-err-val-type.h>
#include <private/pptx-st-tlanimate-motion-path-edit-mode.h>
#include <private/pptx-st-cxn-type.h>
#include <private/pptx-st-crosses.h>
#include <private/pptx-st-bar-grouping.h>
#include <private/pptx-st-tldiagram-build-type.h>
#include <private/pptx-st-algorithm-type.h>
#include <private/pptx-st-function-operator.h>
#include <private/pptx-st-connector-dimension.h>
#include <private/pptx-st-legend-pos.h>
#include <private/pptx-st-scatter-style.h>
#include <private/pptx-st-preset-pattern-val.h>
#include <private/pptx-st-tlanimate-color-direction.h>
#include <private/pptx-st-text-caps-type.h>
#include <private/pptx-st-tlbehavior-additive-type.h>
#include <private/pptx-st-variable-type.h>
#include <private/pptx-st-text-anchor-vertical.h>
#include <private/pptx-st-grouping.h>
#include <private/pptx-st-hue-dir.h>
#include <private/pptx-st-tltrigger-event.h>
#include <private/pptx-st-true-false-blank.h>
#include <private/pptx-st-tlbehavior-override-type.h>
#include <private/pptx-st-blip-compression.h>
#include <private/pptx-st-tlbehavior-accumulate-type.h>
#include <private/pptx-st-animation-dgm-only-build-type.h>
#include <private/pptx-st-node-vertical-alignment.h>
#include <private/pptx-st-text-vertical-type.h>
#include <private/pptx-st-transition-speed.h>
#include <private/pptx-st-calendar-type.h>
#include <private/pptx-st-marker-style.h>
#include <private/pptx-st-hier-branch-style.h>
#include <private/pptx-st-tlcommand-type.h>
#include <private/pptx-st-photo-album-layout.h>
#include <private/pptx-st-tltime-node-type.h>
#include <private/pptx-st-dlbl-pos.h>
#include <private/pptx-st-rect-alignment.h>
#include <private/pptx-st-transition-corner-direction-type.h>
#include <private/pptx-st-bool-operator.h>
#include <private/pptx-st-text-shape-type.h>
#include <private/pptx-st-output-shape-type.h>
#include <private/pptx-st-of-pie-type.h>
#include <private/pptx-st-tltime-node-restart-type.h>
#include <private/pptx-st-page-setup-orientation.h>
#include <private/pptx-st-view-type.h>
#include <private/pptx-st-light-rig-type.h>
#include <private/pptx-st-text-vert-overflow-type.h>
#include <private/pptx-st-tile-flip-mode.h>
#include <private/pptx-st-preset-color-val.h>
#include <private/pptx-st-function-type.h>
#include <private/pptx-st-shape-type.h>
#include <private/pptx-st-splitter-bar-state.h>
#include <private/pptx-st-tlole-chart-build-type.h>
#include <private/pptx-st-disp-blanks-as.h>
#include <private/pptx-st-placeholder-size.h>
#include <private/pptx-st-anim-lvl-str.h>
#include <private/pptx-st-on-off-style-type.h>
#include <private/pptx-st-placeholder-type.h>
#include <private/pptx-st-line-end-width.h>
#include <private/pptx-st-node-horizontal-alignment.h>
#include <private/pptx-st-preset-camera-type.h>
#include <private/pptx-st-tltime-node-sync-type.h>
#include <private/pptx-st-slide-layout-type.h>
#include <private/pptx-st-pitch-family.h>
#include <private/pptx-st-anim-one-str.h>
#include <private/pptx-st-slide-size-type.h>
#include <private/pptx-st-scheme-color-val.h>
#include <private/pptx-st-diagram-horizontal-alignment.h>
#include <private/pptx-st-print-color-mode.h>
#include <private/pptx-st-arrowhead-style.h>
#include <private/pptx-st-vertical-align-run.h>
#include <private/pptx-ct-a-bubble-chart.h>
#include <private/pptx-ct-p-ole-object-link.h>
#include <private/pptx-ct-a-alpha-floor-effect.h>
#include <private/pptx-ct-a-text-underline-fill-group-wrapper.h>
#include <private/pptx-ct-a-gvml-shape.h>
#include <private/pptx-ct-p-control-list.h>
#include <private/pptx-ct-a-text-spacing.h>
#include <private/pptx-ct-a-non-visual-group-drawing-shape-props.h>
#include <private/pptx-ct-a-text-tab-stop-list.h>
#include <private/pptx-ct-a-multi-lvl-str-data.h>
#include <private/pptx-ct-p-tlshape-target-element.h>
#include <private/pptx-ct-a-cell-3d.h>
#include <private/pptx-ct-a-pie-ser.h>
#include <private/pptx-ct-a-group-transform-2d.h>
#include <private/pptx-ct-a-gvml-picture.h>
#include <private/pptx-ct-a-themeable-line-style.h>
#include <private/pptx-ct-a-ser-tx.h>
#include <private/pptx-ct-dgm-sdname.h>
#include <private/pptx-ct-a-table-properties.h>
#include <private/pptx-ct-p-slide-id-list-entry.h>
#include <private/pptx-ct-dgm-color-transform.h>
#include <private/pptx-ct-a-rot-x.h>
#include <private/pptx-ct-a-rot-y.h>
#include <private/pptx-ct-a-path-2d.h>
#include <private/pptx-ct-a-unsigned-int.h>
#include <private/pptx-ct-p-connector.h>
#include <private/pptx-ct-a-fill-properties.h>
#include <private/pptx-ct-a-audio-cdtime.h>
#include <private/pptx-ct-a-table-grid.h>
#include <private/pptx-ct-a-alpha-outset-effect.h>
#include <private/pptx-ct-a-srgb-color.h>
#include <private/pptx-ct-p-custom-show-list.h>
#include <private/pptx-ct-p-notes-master-id-list.h>
#include <private/pptx-ct-a-lbl-algn.h>
#include <private/pptx-ct-dgm-org-chart.h>
#include <private/pptx-ct-p-outline-view-slide-entry.h>
#include <private/pptx-ct-a-font-reference.h>
#include <private/pptx-ct-a-legend-pos.h>
#include <private/pptx-ct-a-scatter-ser.h>
#include <private/pptx-ct-p-orientation-transition.h>
#include <private/pptx-ct-p-slide-master-id-list.h>
#include <private/pptx-ct-a-rel-id.h>
#include <private/pptx-ct-a-skip.h>
#include <private/pptx-ct-p-group-shape-non-visual.h>
#include <private/pptx-ct-p-tltime-target-element.h>
#include <private/pptx-ct-a-connection-site.h>
#include <private/pptx-ct-a-tick-mark.h>
#include <private/pptx-ct-p-tlby-rgb-color-transform.h>
#include <private/pptx-ct-p-customer-data.h>
#include <private/pptx-ct-p-extension-list.h>
#include <private/pptx-ct-a-inverse-gamma-transform.h>
#include <private/pptx-ct-a-no-fill-properties.h>
#include <private/pptx-ct-a-path-2dlist.h>
#include <private/pptx-ct-cdr-graphic-frame-non-visual.h>
#include <private/pptx-ct-cdr-connector-non-visual.h>
#include <private/pptx-ct-a-extension.h>
#include <private/pptx-ct-p-tlcommon-media-node-data.h>
#include <private/pptx-ct-a-tx.h>
#include <private/pptx-ct-a-bar-3dchart.h>
#include <private/pptx-ct-p-outline-view-slide-list.h>
#include <private/pptx-ct-a-clipboard-style-sheet.h>
#include <private/pptx-ct-a-color-mapping-override.h>
#include <private/pptx-ct-p-comment.h>
#include <private/pptx-ct-a-preset-text-shape.h>
#include <private/pptx-ct-a-animation-chart-element.h>
#include <private/pptx-ct-a-default-shape-definition.h>
#include <private/pptx-ct-p-picture.h>
#include <private/pptx-ct-p-tlmedia-node-video.h>
#include <private/pptx-ct-p-handout-master-id-list-entry.h>
#include <private/pptx-ct-a-positive-percentage.h>
#include <private/pptx-ct-cdr-group-shape.h>
#include <private/pptx-ct-p-transition-start-sound-action.h>
#include <private/pptx-ct-p-handout-master.h>
#include <private/pptx-ct-dgm-diagram-definition-header-lst.h>
#include <private/pptx-ct-p-shape.h>
#include <private/pptx-ct-a-print-settings.h>
#include <private/pptx-ct-p-time-node-list.h>
#include <private/pptx-ct-p-picture-non-visual.h>
#include <private/pptx-ct-dgm-sdcategories.h>
#include <private/pptx-ct-a-animation-dgm-element.h>
#include <private/pptx-ct-p-normal-view-properties.h>
#include <private/pptx-ct-a-effect-properties.h>
#include <private/pptx-ct-p-connector-non-visual.h>
#include <private/pptx-ct-a-text-paragraph.h>
#include <private/pptx-ct-a-camera.h>
#include <private/pptx-ct-a-gradient-stop.h>
#include <private/pptx-ct-a-pivot-fmts.h>
#include <private/pptx-ct-a-alpha-ceiling-effect.h>
#include <private/pptx-ct-p-common-slide-data.h>
#include <private/pptx-ct-a-blur-effect.h>
#include <private/pptx-ct-p-slide-layout-id-list-entry.h>
#include <private/pptx-ct-a-text-spacing-point.h>
#include <private/pptx-ct-a-text-shape-autofit.h>
#include <private/pptx-ct-a-connection.h>
#include <private/pptx-ct-a-gvml-use-shape-rectangle.h>
#include <private/pptx-ct-p-eight-direction-transition.h>
#include <private/pptx-ct-p-web-properties.h>
#include <private/pptx-ct-a-positive-fixed-percentage.h>
#include <private/pptx-ct-dgm-rules.h>
#include <private/pptx-ct-a-surface.h>
#include <private/pptx-ct-a-depth-percent.h>
#include <private/pptx-ct-p-tltext-target-element.h>
#include <private/pptx-ct-p-comment-author-list.h>
#include <private/pptx-ct-p-graphical-object-frame.h>
#include <private/pptx-ct-a-dlbls.h>
#include <private/pptx-ct-a-background-fill-style-list.h>
#include <private/pptx-ct-p-tlby-animate-color-transform.h>
#include <private/pptx-ct-a-color-scheme-list.h>
#include <private/pptx-ct-a-non-visual-drawing-shape-props.h>
#include <private/pptx-ct-dgm-constraints.h>
#include <private/pptx-ct-a-alpha-replace-effect.h>
#include <private/pptx-ct-p-guide.h>
#include <private/pptx-ct-a-point-3d.h>
#include <private/pptx-ct-a-adj-point-2d.h>
#include <private/pptx-ct-a-gamma-transform.h>
#include <private/pptx-ct-a-pivot-fmt.h>
#include <private/pptx-ct-a-non-visual-connector-properties.h>
#include <private/pptx-ct-dgm-algorithm.h>
#include <private/pptx-ct-a-line-join-round.h>
#include <private/pptx-ct-a-path-2dcubic-bezier-to.h>
#include <private/pptx-ct-a-picture-options.h>
#include <private/pptx-ct-a-quick-time-file.h>
#include <private/pptx-ct-a-effect-reference.h>
#include <private/pptx-ct-a-crosses.h>
#include <private/pptx-ct-a-trendline.h>
#include <private/pptx-ct-p-slide-timing.h>
#include <private/pptx-ct-a-color-mapping.h>
#include <private/pptx-ct-a-stretch-info-properties.h>
#include <private/pptx-ct-dgm-style-label.h>
#include <private/pptx-ct-a-table-cell-properties.h>
#include <private/pptx-ct-a-boolean.h>
#include <private/pptx-ct-a-blip.h>
#include <private/pptx-ct-a-table-style-text-style.h>
#include <private/pptx-ct-a-connection-site-list.h>
#include <private/pptx-ct-a-effect-list.h>
#include <private/pptx-ct-p-tags-data.h>
#include <private/pptx-ct-a-gradient-stop-list.h>
#include <private/pptx-ct-a-scheme-color.h>
#include <private/pptx-ct-a-line-ser.h>
#include <private/pptx-ct-a-percentage.h>
#include <private/pptx-ct-a-text-normal-autofit.h>
#include <private/pptx-ct-cdr-shape.h>
#include <private/pptx-ct-a-base-styles.h>
#include <private/pptx-ct-p-tliterate-interval-time.h>
#include <private/pptx-ct-dgm-colors.h>
#include <private/pptx-ct-a-legend.h>
#include <private/pptx-ct-a-glow-effect.h>
#include <private/pptx-ct-a-color-scheme-and-mapping.h>
#include <private/pptx-ct-p-tlcommon-behavior-data.h>
#include <private/pptx-ct-p-tag-list.h>
#include <private/pptx-ct-a-gradient-fill-properties.h>
#include <private/pptx-ct-a-style-matrix.h>
#include <private/pptx-ct-a-content-part-locking.h>
#include <private/pptx-ct-a-linear-shade-properties.h>
#include <private/pptx-ct-a-text-no-bullet.h>
#include <private/pptx-ct-a-page-setup.h>
#include <private/pptx-ct-p-tlanimate-motion-behavior.h>
#include <private/pptx-ct-a-scatter-chart.h>
#include <private/pptx-ct-p-tltime-node-parallel.h>
#include <private/pptx-ct-p-embedded-font-data-id.h>
#include <private/pptx-ct-a-complement-transform.h>
#include <private/pptx-ct-a-table-part-style.h>
#include <private/pptx-ct-p-notes-slide.h>
#include <private/pptx-ct-p-show-info-browse.h>
#include <private/pptx-ct-cdr-rel-size-anchor.h>
#include <private/pptx-ct-a-bar-dir.h>
#include <private/pptx-ct-a-transform-2d.h>
#include <private/pptx-ct-a-animation-element-choice.h>
#include <private/pptx-ct-dgm-layout-variable-property-set.h>
#include <private/pptx-ct-a-ratio.h>
#include <private/pptx-ct-a-inverse-transform.h>
#include <private/pptx-ct-a-style-matrix-reference.h>
#include <private/pptx-ct-a-angle.h>
#include <private/pptx-ct-p-ole-object-embed.h>
#include <private/pptx-ct-a-system-color.h>
#include <private/pptx-ct-a-gvml-group-shape.h>
#include <private/pptx-ct-a-multi-lvl-str-ref.h>
#include <private/pptx-ct-a-soft-edges-effect.h>
#include <private/pptx-ct-a-disp-units.h>
#include <private/pptx-ct-p-shape-non-visual.h>
#include <private/pptx-ct-p-graphical-object-frame-non-visual.h>
#include <private/pptx-ct-a-text-font.h>
#include <private/pptx-ct-a-num-fmt.h>
#include <private/pptx-ct-a-light-rig.h>
#include <private/pptx-ct-a-doughnut-chart.h>
#include <private/pptx-ct-a-group-fill-properties.h>
#include <private/pptx-ct-a-geom-guide.h>
#include <private/pptx-ct-a-period.h>
#include <private/pptx-ct-a-color-change-effect.h>
#include <private/pptx-ct-a-shape-style.h>
#include <private/pptx-ct-a-gap-amount.h>
#include <private/pptx-ct-a-line-style-list.h>
#include <private/pptx-ct-dgm-description.h>
#include <private/pptx-ct-p-show-info-kiosk.h>
#include <private/pptx-ct-a-table-style.h>
#include <private/pptx-ct-a-text-language-id.h>
#include <private/pptx-ct-a-text-tab-stop.h>
#include <private/pptx-ct-a-group-locking.h>
#include <private/pptx-ct-a-table-col.h>
#include <private/pptx-ct-a-audio-cd.h>
#include <private/pptx-ct-dsp-drawing.h>
#include <private/pptx-ct-p-custom-show.h>
#include <private/pptx-ct-cdr-group-shape-non-visual.h>
#include <private/pptx-ct-p-slide-relationship-list-entry.h>
#include <private/pptx-ct-a-err-bar-type.h>
#include <private/pptx-ct-a-hsleffect.h>
#include <private/pptx-ct-a-cross-between.h>
#include <private/pptx-ct-a-object-style-defaults.h>
#include <private/pptx-ct-p-empty.h>
#include <private/pptx-ct-a-scale-2d.h>
#include <private/pptx-ct-p-kinsoku.h>
#include <private/pptx-ct-p-tlbehavior-attribute-name-list.h>
#include <private/pptx-ct-a-pivot-source.h>
#include <private/pptx-ct-p-custom-show-id.h>
#include <private/pptx-ct-a-shape-locking.h>
#include <private/pptx-ct-dgm-categories.h>
#include <private/pptx-ct-p-tlanimate-behavior.h>
#include <private/pptx-ct-a-page-margins.h>
#include <private/pptx-ct-p-slide-master-text-styles.h>
#include <private/pptx-ct-a-alpha-bi-level-effect.h>
#include <private/pptx-ct-a-layout-mode.h>
#include <private/pptx-ct-p-slide-relationship-list.h>
#include <private/pptx-ct-p-background-properties.h>
#include <private/pptx-ct-dgm-anim-one.h>
#include <private/pptx-ct-a-animation-dgm-build-properties.h>
#include <private/pptx-ct-a-text-bullet-size-point.h>
#include <private/pptx-ct-a-graphical-object-frame-locking.h>
#include <private/pptx-ct-a-reflection-effect.h>
#include <private/pptx-ct-a-gvml-graphic-frame-non-visual.h>
#include <private/pptx-ct-a-ax-data-source.h>
#include <private/pptx-ct-a-color-replace-effect.h>
#include <private/pptx-ct-a-title.h>
#include <private/pptx-ct-p-html-publish-properties.h>
#include <private/pptx-ct-a-polar-adjust-handle.h>
#include <private/pptx-ct-p-slide-id-list.h>
#include <private/pptx-ct-dgm-cxn.h>
#include <private/pptx-ct-a-text-field.h>
#include <private/pptx-ct-p-tltime-node-exclusive.h>
#include <private/pptx-ct-a-color.h>
#include <private/pptx-ct-p-side-direction-transition.h>
#include <private/pptx-ct-a-shape-properties.h>
#include <private/pptx-ct-a-video-file.h>
#include <private/pptx-ct-a-text-bullet-size-follow-text.h>
#include <private/pptx-ct-a-luminance-effect.h>
#include <private/pptx-ct-a-effect-style-item.h>
#include <private/pptx-ct-a-text-line-break.h>
#include <private/pptx-ct-cdr-abs-size-anchor.h>
#include <private/pptx-ct-a-geom-guide-list.h>
#include <private/pptx-ct-a-solid-color-fill-properties.h>
#include <private/pptx-ct-a-thickness.h>
#include <private/pptx-ct-p-optional-black-transition.h>
#include <private/pptx-ct-p-comment-author.h>
#include <private/pptx-ct-p-tlbuild-paragraph.h>
#include <private/pptx-ct-dgm-cxn-list.h>
#include <private/pptx-ct-a-dpt.h>
#include <private/pptx-ct-a-outer-shadow-effect.h>
#include <private/pptx-ct-dgm-color-transform-header-lst.h>
#include <private/pptx-ct-p-slide-transition.h>
#include <private/pptx-ct-a-grouping.h>
#include <private/pptx-ct-p-tlsub-shape-id.h>
#include <private/pptx-ct-a-graphical-object.h>
#include <private/pptx-ct-a-font-collection.h>
#include <private/pptx-ct-dgm-diagram-definition-header.h>
#include <private/pptx-ct-p-tlanim-variant-string-val.h>
#include <private/pptx-ct-a-preset-shadow-effect.h>
#include <private/pptx-ct-a-val-ax.h>
#include <private/pptx-ct-a-path-2darc-to.h>
#include <private/pptx-ct-a-table-background-style.h>
#include <private/pptx-ct-a-path-shade-properties.h>
#include <private/pptx-ct-a-blip-fill-properties.h>
#include <private/pptx-ct-a-text-spacing-percent.h>
#include <private/pptx-ct-dgm-anim-lvl.h>
#include <private/pptx-ct-a-picture-locking.h>
#include <private/pptx-ct-p-tlanimate-color-behavior.h>
#include <private/pptx-ct-a-graphical-object-data.h>
#include <private/pptx-ct-p-outline-view-properties.h>
#include <private/pptx-ct-p-photo-album.h>
#include <private/pptx-ct-a-marker-size.h>
#include <private/pptx-ct-a-supplemental-font.h>
#include <private/pptx-ct-a-marker.h>
#include <private/pptx-ct-a-picture-stack-unit.h>
#include <private/pptx-ct-a-audio-file.h>
#include <private/pptx-ct-a-xyadjust-handle.h>
#include <private/pptx-ct-p-tlole-build-chart.h>
#include <private/pptx-ct-cdr-graphic-frame.h>
#include <private/pptx-ct-a-positive-fixed-angle.h>
#include <private/pptx-ct-dgm-otherwise.h>
#include <private/pptx-ct-dgm-ctstyle-label.h>
#include <private/pptx-ct-a-blend-effect.h>
#include <private/pptx-ct-a-text-char-bullet.h>
#include <private/pptx-ct-a-regular-text-run.h>
#include <private/pptx-ct-p-common-view-properties.h>
#include <private/pptx-ct-a-text-bullet-typeface-follow-text.h>
#include <private/pptx-ct-a-color-scheme.h>
#include <private/pptx-ct-p-extension-list-modify.h>
#include <private/pptx-ct-a-dlbl.h>
#include <private/pptx-ct-p-extension.h>
#include <private/pptx-ct-a-table-row.h>
#include <private/pptx-ct-p-embedded-font-list-entry.h>
#include <private/pptx-ct-a-transform-effect.h>
#include <private/pptx-ct-a-bar-ser.h>
#include <private/pptx-ct-p-common-slide-view-properties.h>
#include <private/pptx-ct-a-style.h>
#include <private/pptx-ct-cdr-picture-non-visual.h>
#include <private/pptx-ct-p-tlset-behavior.h>
#include <private/pptx-ct-a-chart-space.h>
#include <private/pptx-ct-a-line-chart.h>
#include <private/pptx-ct-a-fixed-percentage.h>
#include <private/pptx-ct-a-custom-color.h>
#include <private/pptx-ct-p-show-properties.h>
#include <private/pptx-ct-p-modify-verifier.h>
#include <private/pptx-ct-a-surface-3dchart.h>
#include <private/pptx-ct-a-duotone-effect.h>
#include <private/pptx-ct-p-in-out-transition.h>
#include <private/pptx-ct-a-dash-stop.h>
#include <private/pptx-ct-dgm-direction.h>
#include <private/pptx-ct-p-notes-master-id-list-entry.h>
#include <private/pptx-ct-a-color-mru.h>
#include <private/pptx-ct-p-tltime-animate-value-list.h>
#include <private/pptx-ct-a-embedded-wavaudio-file.h>
#include <private/pptx-ct-a-non-visual-content-part-properties.h>
#include <private/pptx-ct-a-sc-rgb-color.h>
#include <private/pptx-ct-dgm-hier-branch-style.h>
#include <private/pptx-ct-dgm-diagram-definition.h>
#include <private/pptx-ct-dgm-sddescription.h>
#include <private/pptx-ct-a-background-formatting.h>
#include <private/pptx-ct-a-hsl-color.h>
#include <private/pptx-ct-dgm-name.h>
#include <private/pptx-ct-p-split-transition.h>
#include <private/pptx-ct-p-presentation.h>
#include <private/pptx-ct-cdr-marker.h>
#include <private/pptx-ct-a-disp-units-lbl.h>
#include <private/pptx-ct-a-lbl-offset.h>
#include <private/pptx-ct-p-tlmedia-node-audio.h>
#include <private/pptx-ct-dgm-bullet-enabled.h>
#include <private/pptx-ct-dgm-pt-list.h>
#include <private/pptx-ct-a-radar-chart.h>
#include <private/pptx-ct-p-smart-tags.h>
#include <private/pptx-ct-a-text-bullet-size-percent.h>
#include <private/pptx-ct-a-line-3dchart.h>
#include <private/pptx-ct-p-tltime-condition-list.h>
#include <private/pptx-ct-a-table-cell.h>
#include <private/pptx-ct-dgm-presentation-of.h>
#include <private/pptx-ct-dgm-style-definition-header.h>
#include <private/pptx-ct-a-non-visual-drawing-props.h>
#include <private/pptx-ct-a-surface-ser.h>
#include <private/pptx-ct-a-text-character-properties.h>
#include <private/pptx-ct-a-surface-chart.h>
#include <private/pptx-ct-a-gvml-group-shape-non-visual.h>
#include <private/pptx-ct-a-text-underline-fill-follow-text.h>
#include <private/pptx-ct-a-date-ax.h>
#include <private/pptx-ct-a-table-style-cell-style.h>
#include <private/pptx-ct-p-corner-direction-transition.h>
#include <private/pptx-ct-a-str-data.h>
#include <private/pptx-ct-p-tltime-node-sequence.h>
#include <private/pptx-ct-a-text-underline-line-follow-text.h>
#include <private/pptx-ct-p-print-properties.h>
#include <private/pptx-ct-dgm-choose.h>
#include <private/pptx-ct-a-bubble-ser.h>
#include <private/pptx-ct-dgm-category.h>
#include <private/pptx-ct-a-gvml-graphical-object-frame.h>
#include <private/pptx-ct-p-tltime-condition.h>
#include <private/pptx-ct-p-slide.h>
#include <private/pptx-ct-a-second-pie-size.h>
#include <private/pptx-ct-a-text-body.h>
#include <private/pptx-ct-dgm-sdcategory.h>
#include <private/pptx-ct-a-table-cell-border-style.h>
#include <private/pptx-ct-a-path-2dquad-bezier-to.h>
#include <private/pptx-ct-p-header-footer.h>
#include <private/pptx-ct-p-group-shape.h>
#include <private/pptx-ct-a-bar-grouping.h>
#include <private/pptx-ct-p-view-properties.h>
#include <private/pptx-ct-a-shape-3d.h>
#include <private/pptx-ct-a-path-2dline-to.h>
#include <private/pptx-ct-a-layout-target.h>
#include <private/pptx-ct-a-up-down-bar.h>
#include <private/pptx-ct-a-preset-color.h>
#include <private/pptx-ct-a-geom-rect.h>
#include <private/pptx-ct-p-notes-view-properties.h>
#include <private/pptx-ct-a-marker-style.h>
#include <private/pptx-ct-a-size-represents.h>
#include <private/pptx-ct-dgm-ctcategory.h>
#include <private/pptx-ct-a-str-val.h>
#include <private/pptx-ct-cdr-connector.h>
#include <private/pptx-ct-a-sphere-coords.h>
#include <private/pptx-ct-dgm-ctcategories.h>
#include <private/pptx-ct-a-extension-list.h>
#include <private/pptx-ct-a-double.h>
#include <private/pptx-ct-a-overlap.h>
#include <private/pptx-ct-dgm-child-pref.h>
#include <private/pptx-ct-p-tlpoint.h>
#include <private/pptx-ct-p-slide-layout.h>
#include <private/pptx-ct-a-empty-element.h>
#include <private/pptx-ct-a-inner-shadow-effect.h>
#include <private/pptx-ct-a-legend-entry.h>
#include <private/pptx-ct-a-trendline-lbl.h>
#include <private/pptx-ct-dgm-rel-ids.h>
#include <private/pptx-ct-a-table-style-list.h>
#include <private/pptx-ct-a-preset-geometry-2d.h>
#include <private/pptx-ct-a-gvml-connector-non-visual.h>
#include <private/pptx-ct-p-slide-sorter-view-properties.h>
#include <private/pptx-ct-a-pattern-fill-properties.h>
#include <private/pptx-ct-a-hpercent.h>
#include <private/pptx-ct-a-cat-ax.h>
#include <private/pptx-ct-a-num-data-source.h>
#include <private/pptx-ct-dgm-data-model.h>
#include <private/pptx-ct-a-animation-graphical-object-build-properties.h>
#include <private/pptx-ct-p-tlgraphical-object-build.h>
#include <private/pptx-ct-a-office-art-extension.h>
#include <private/pptx-ct-a-tile-info-properties.h>
#include <private/pptx-ct-a-lvl.h>
#include <private/pptx-ct-a-path-2dclose.h>
#include <private/pptx-ct-dgm-numeric-rule.h>
#include <private/pptx-ct-a-gvml-text-shape.h>
#include <private/pptx-ct-a-non-visual-graphic-frame-properties.h>
#include <private/pptx-ct-dgm-constraint.h>
#include <private/pptx-ct-dgm-elem-prop-set.h>
#include <private/pptx-ct-a-band-fmt.h>
#include <private/pptx-ct-p-tlbuild-diagram.h>
#include <private/pptx-ct-dgm-child-max.h>
#include <private/pptx-ct-a-pie-chart.h>
#include <private/pptx-ct-p-slide-master.h>
#include <private/pptx-ct-dsp-shape-non-visual.h>
#include <private/pptx-ct-p-slide-master-id-list-entry.h>
#include <private/pptx-ct-a-chart.h>
#include <private/pptx-ct-a-manual-layout.h>
#include <private/pptx-ct-dgm-layout-node.h>
#include <private/pptx-ct-a-vector-3d.h>
#include <private/pptx-ct-p-slide-size.h>
#include <private/pptx-ct-a-fill-overlay-effect.h>
#include <private/pptx-ct-a-backdrop.h>
#include <private/pptx-ct-p-wheel-transition.h>
#include <private/pptx-ct-a-axis-unit.h>
#include <private/pptx-ct-a-log-base.h>
#include <private/pptx-ct-p-normal-view-portion.h>
#include <private/pptx-ct-a-radar-ser.h>
#include <private/pptx-ct-a-scatter-style.h>
#include <private/pptx-ct-a-bar-chart.h>
#include <private/pptx-ct-a-non-visual-picture-properties.h>
#include <private/pptx-ct-a-hyperlink.h>
#include <private/pptx-ct-a-of-pie-chart.h>
#include <private/pptx-ct-a-cust-split.h>
#include <private/pptx-ct-a-built-in-unit.h>
#include <private/pptx-ct-p-notes-text-view-properties.h>
#include <private/pptx-ct-a-text-body-properties.h>
#include <private/pptx-ct-a-area-chart.h>
#include <private/pptx-ct-a-line-end-properties.h>
#include <private/pptx-ct-a-up-down-bars.h>
#include <private/pptx-ct-p-presentation-properties.h>
#include <private/pptx-ct-a-line-properties.h>
#include <private/pptx-ct-a-perspective.h>
#include <private/pptx-ct-a-area-ser.h>
#include <private/pptx-ct-p-application-non-visual-drawing-props.h>
#include <private/pptx-ct-p-slide-sync-properties.h>
#include <private/pptx-ct-p-tlanim-variant-float-val.h>
#include <private/pptx-ct-a-tint-effect.h>
#include <private/pptx-ct-a-font-scheme.h>
#include <private/pptx-ct-p-tltrigger-time-node-id.h>
#include <private/pptx-ct-a-text-list-style.h>
#include <private/pptx-ct-dgm-style-definition.h>
#include <private/pptx-ct-a-bubble-scale.h>
#include <private/pptx-ct-a-preset-line-dash-properties.h>
#include <private/pptx-ct-a-alpha-modulate-fixed-effect.h>
#include <private/pptx-ct-a-split-type.h>
#include <private/pptx-ct-a-text-paragraph-properties.h>
#include <private/pptx-ct-p-placeholder.h>
#include <private/pptx-ct-p-guide-list.h>
#include <private/pptx-ct-a-text-autonumber-bullet.h>
#include <private/pptx-ct-a-custom-geometry-2d.h>
#include <private/pptx-ct-p-tlole-chart-target-element.h>
#include <private/pptx-ct-cdr-shape-non-visual.h>
#include <private/pptx-ct-p-tliterate-interval-percentage.h>
#include <private/pptx-ct-p-tlanim-variant.h>
#include <private/pptx-ct-a-err-dir.h>
#include <private/pptx-ct-p-tlanim-variant-integer-val.h>
#include <private/pptx-ct-p-tltime-animate-value.h>
#include <private/pptx-ct-a-err-val-type.h>
#include <private/pptx-ct-a-fill-style-list.h>
#include <private/pptx-ct-dsp-group-shape.h>
#include <private/pptx-ct-a-chart-lines.h>
#include <private/pptx-ct-dsp-group-shape-non-visual.h>
#include <private/pptx-ct-a-num-data.h>
#include <private/pptx-ct-dgm-pt.h>
#include <private/pptx-ct-dgm-sample-data.h>
#include <private/pptx-ct-p-tltrigger-runtime-node.h>
#include <private/pptx-ct-a-effect-container.h>
#include <private/pptx-ct-a-office-style-sheet.h>
#include <private/pptx-ct-a-adjust-handle-list.h>
#include <private/pptx-ct-p-tlcommand-behavior.h>
#include <private/pptx-ct-dgm-resize-handles.h>
#include <private/pptx-ct-a-path-2dmove-to.h>
#include <private/pptx-ct-a-grayscale-transform.h>
#include <private/pptx-ct-a-whole-e2o-formatting.h>
#include <private/pptx-ct-p-background.h>
#include <private/pptx-ct-a-flat-text.h>
#include <private/pptx-ct-dgm-shape.h>
#include <private/pptx-ct-dgm-ctdescription.h>
#include <private/pptx-ct-a-alpha-modulate-effect.h>
#include <private/pptx-ct-a-line-join-bevel.h>
#include <private/pptx-ct-a-relative-offset-effect.h>
#include <private/pptx-ct-cdr-picture.h>
#include <private/pptx-ct-p-embedded-font-list.h>
#include <private/pptx-ct-a-bevel.h>
#include <private/pptx-ct-a-err-bars.h>
#include <private/pptx-ct-dgm-parameter.h>
#include <private/pptx-ct-a-line-join-miter-properties.h>
#include <private/pptx-ct-p-tliterate-data.h>
#include <private/pptx-ct-a-dtable.h>
#include <private/pptx-ct-a-tick-lbl-pos.h>
#include <private/pptx-ct-a-order.h>
#include <private/pptx-ct-a-shape.h>
#include <private/pptx-ct-p-ole-object.h>
#include <private/pptx-ct-a-time-unit.h>
#include <private/pptx-ct-a-picture-non-visual.h>
#include <private/pptx-ct-p-rel.h>
#include <private/pptx-ct-p-notes-master.h>
#include <private/pptx-ct-a-dash-stop-list.h>
#include <private/pptx-ct-a-gvml-shape-non-visual.h>
#include <private/pptx-ct-a-relative-rect.h>
#include <private/pptx-ct-a-dlbl-pos.h>
#include <private/pptx-ct-a-hole-size.h>
#include <private/pptx-ct-p-tlanim-variant-boolean-val.h>
#include <private/pptx-ct-a-trendline-type.h>
#include <private/pptx-ct-p-customer-data-list.h>
#include <private/pptx-ct-dgm-adj.h>
#include <private/pptx-ct-a-connector-locking.h>
#include <private/pptx-ct-a-text-blip-bullet.h>
#include <private/pptx-ct-dgm-adj-lst.h>
#include <private/pptx-ct-p-index-range.h>
#include <private/pptx-ct-a-effect-style-list.h>
#include <private/pptx-ct-a-header-footer.h>
#include <private/pptx-ct-a-picture.h>
#include <private/pptx-ct-dsp-data-model-ext-block.h>
#include <private/pptx-ct-a-table.h>
#include <private/pptx-ct-dsp-shape.h>
#include <private/pptx-ct-a-view-3d.h>
#include <private/pptx-ct-a-external-data.h>
#include <private/pptx-ct-p-slide-view-properties.h>
#include <private/pptx-ct-p-tlby-hsl-color-transform.h>
#include <private/pptx-ct-p-tlanimate-rotation-behavior.h>
#include <private/pptx-ct-dgm-style-definition-header-lst.h>
#include <private/pptx-ct-a-first-slice-ang.h>
#include <private/pptx-ct-p-handout-master-id-list.h>
#include <private/pptx-ct-a-custom-color-list.h>
#include <private/pptx-ct-a-scaling.h>
#include <private/pptx-ct-a-positive-size-2d.h>
#include <private/pptx-ct-p-tlanimate-effect-behavior.h>
#include <private/pptx-ct-a-text-bullet-color-follow-text.h>
#include <private/pptx-ct-a-num-ref.h>
#include <private/pptx-ct-a-pie-3dchart.h>
#include <private/pptx-ct-a-fill-effect.h>
#include <private/pptx-ct-a-base-styles-override.h>
#include <private/pptx-ct-a-plot-area.h>
#include <private/pptx-ct-p-tlcommon-time-node-data.h>
#include <private/pptx-ct-p-control.h>
#include <private/pptx-ct-a-str-ref.h>
#include <private/pptx-ct-a-num-val.h>
#include <private/pptx-ct-a-layout.h>
#include <private/pptx-ct-dgm-for-each.h>
#include <private/pptx-ct-dgm-ctname.h>
#include <private/pptx-ct-p-tltemplate.h>
#include <private/pptx-ct-p-build-list.h>
#include <private/pptx-ct-dgm-when.h>
#include <private/pptx-ct-a-stock-chart.h>
#include <private/pptx-ct-p-tlanimate-scale-behavior.h>
#include <private/pptx-ct-a-band-fmts.h>
#include <private/pptx-ct-a-protection.h>
#include <private/pptx-ct-a-group-shape-properties.h>
#include <private/pptx-ct-a-headers.h>
#include <private/pptx-ct-a-disp-blanks-as.h>
#include <private/pptx-ct-a-bi-level-effect.h>
#include <private/pptx-ct-cdr-drawing.h>
#include <private/pptx-ct-dgm-text-props.h>
#include <private/pptx-ct-p-transition-sound-action.h>
#include <private/pptx-ct-a-of-pie-type.h>
#include <private/pptx-ct-a-text-no-autofit.h>
#include <private/pptx-ct-a-picture-format.h>
#include <private/pptx-ct-p-comment-list.h>
#include <private/pptx-ct-a-radar-style.h>
#include <private/pptx-ct-a-animation-chart-build-properties.h>
#include <private/pptx-ct-a-gvml-picture-non-visual.h>
#include <private/pptx-ct-a-ser-ax.h>
#include <private/pptx-ct-a-ax-pos.h>
#include <private/pptx-ct-p-string-tag.h>
#include <private/pptx-ct-a-point-2d.h>
#include <private/pptx-ct-a-office-art-extension-list.h>
#include <private/pptx-ct-a-alpha-inverse-effect.h>
#include <private/pptx-ct-a-orientation.h>
#include <private/pptx-ct-p-slide-layout-id-list.h>
#include <private/pptx-ct-a-gvml-connector.h>
#include <private/pptx-ct-a-area-3dchart.h>
#include <private/pptx-ct-a-scene-3d.h>
#include <private/pptx-ct-a-grayscale-effect.h>
#include <private/pptx-ct-dgm-color-transform-header.h>
#include <private/pptx-ct-p-tltemplate-list.h>
#include <private/pptx-any.h>

#endif /* __PPTX_H__ */
