#define __PPTX_PRIVATE_INCLUDES__ /* Allow private includes */
/* Standard headers */
#include <string.h>
/* Self header */
#include <private/pptx-st-shape-type.h>
/* Imported internal stuff */

struct map {
    char *key;
    pptx_st_shape_type_token_enum value;
};

static int
comparator(const void *const lhs, const void *const rhs)
{
    return strcmp(((struct map *) lhs)->key, ((struct map *) rhs)->key);

}

pptx_st_shape_type_token_enum
pptx_get_st_shape_type(xmlNode *node, const xmlChar *property)
{
    struct map *found;
    struct map key;
    struct map base[188] = {
      {"accentBorderCallout1", ST_SHAPE_TYPE_ACCENT_BORDER_CALLOUT1},
      {"accentBorderCallout2", ST_SHAPE_TYPE_ACCENT_BORDER_CALLOUT2},
      {"accentBorderCallout3", ST_SHAPE_TYPE_ACCENT_BORDER_CALLOUT3},
      {"accentCallout1", ST_SHAPE_TYPE_ACCENT_CALLOUT1},
      {"accentCallout2", ST_SHAPE_TYPE_ACCENT_CALLOUT2},
      {"accentCallout3", ST_SHAPE_TYPE_ACCENT_CALLOUT3},
      {"actionButtonBackPrevious", ST_SHAPE_TYPE_ACTION_BUTTON_BACK_PREVIOUS},
      {"actionButtonBeginning", ST_SHAPE_TYPE_ACTION_BUTTON_BEGINNING},
      {"actionButtonBlank", ST_SHAPE_TYPE_ACTION_BUTTON_BLANK},
      {"actionButtonDocument", ST_SHAPE_TYPE_ACTION_BUTTON_DOCUMENT},
      {"actionButtonEnd", ST_SHAPE_TYPE_ACTION_BUTTON_END},
      {"actionButtonForwardNext", ST_SHAPE_TYPE_ACTION_BUTTON_FORWARD_NEXT},
      {"actionButtonHelp", ST_SHAPE_TYPE_ACTION_BUTTON_HELP},
      {"actionButtonHome", ST_SHAPE_TYPE_ACTION_BUTTON_HOME},
      {"actionButtonInformation", ST_SHAPE_TYPE_ACTION_BUTTON_INFORMATION},
      {"actionButtonMovie", ST_SHAPE_TYPE_ACTION_BUTTON_MOVIE},
      {"actionButtonReturn", ST_SHAPE_TYPE_ACTION_BUTTON_RETURN},
      {"actionButtonSound", ST_SHAPE_TYPE_ACTION_BUTTON_SOUND},
      {"arc", ST_SHAPE_TYPE_ARC},
      {"bentArrow", ST_SHAPE_TYPE_BENT_ARROW},
      {"bentConnector2", ST_SHAPE_TYPE_BENT_CONNECTOR2},
      {"bentConnector3", ST_SHAPE_TYPE_BENT_CONNECTOR3},
      {"bentConnector4", ST_SHAPE_TYPE_BENT_CONNECTOR4},
      {"bentConnector5", ST_SHAPE_TYPE_BENT_CONNECTOR5},
      {"bentUpArrow", ST_SHAPE_TYPE_BENT_UP_ARROW},
      {"bevel", ST_SHAPE_TYPE_BEVEL},
      {"blockArc", ST_SHAPE_TYPE_BLOCK_ARC},
      {"borderCallout1", ST_SHAPE_TYPE_BORDER_CALLOUT1},
      {"borderCallout2", ST_SHAPE_TYPE_BORDER_CALLOUT2},
      {"borderCallout3", ST_SHAPE_TYPE_BORDER_CALLOUT3},
      {"bracePair", ST_SHAPE_TYPE_BRACE_PAIR},
      {"bracketPair", ST_SHAPE_TYPE_BRACKET_PAIR},
      {"callout1", ST_SHAPE_TYPE_CALLOUT1},
      {"callout2", ST_SHAPE_TYPE_CALLOUT2},
      {"callout3", ST_SHAPE_TYPE_CALLOUT3},
      {"can", ST_SHAPE_TYPE_CAN},
      {"chartPlus", ST_SHAPE_TYPE_CHART_PLUS},
      {"chartStar", ST_SHAPE_TYPE_CHART_STAR},
      {"chartX", ST_SHAPE_TYPE_CHART_X},
      {"chevron", ST_SHAPE_TYPE_CHEVRON},
      {"chord", ST_SHAPE_TYPE_CHORD},
      {"circularArrow", ST_SHAPE_TYPE_CIRCULAR_ARROW},
      {"cloud", ST_SHAPE_TYPE_CLOUD},
      {"cloudCallout", ST_SHAPE_TYPE_CLOUD_CALLOUT},
      {"corner", ST_SHAPE_TYPE_CORNER},
      {"cornerTabs", ST_SHAPE_TYPE_CORNER_TABS},
      {"cube", ST_SHAPE_TYPE_CUBE},
      {"curvedConnector2", ST_SHAPE_TYPE_CURVED_CONNECTOR2},
      {"curvedConnector3", ST_SHAPE_TYPE_CURVED_CONNECTOR3},
      {"curvedConnector4", ST_SHAPE_TYPE_CURVED_CONNECTOR4},
      {"curvedConnector5", ST_SHAPE_TYPE_CURVED_CONNECTOR5},
      {"curvedDownArrow", ST_SHAPE_TYPE_CURVED_DOWN_ARROW},
      {"curvedLeftArrow", ST_SHAPE_TYPE_CURVED_LEFT_ARROW},
      {"curvedRightArrow", ST_SHAPE_TYPE_CURVED_RIGHT_ARROW},
      {"curvedUpArrow", ST_SHAPE_TYPE_CURVED_UP_ARROW},
      {"decagon", ST_SHAPE_TYPE_DECAGON},
      {"diagStripe", ST_SHAPE_TYPE_DIAG_STRIPE},
      {"diamond", ST_SHAPE_TYPE_DIAMOND},
      {"dodecagon", ST_SHAPE_TYPE_DODECAGON},
      {"donut", ST_SHAPE_TYPE_DONUT},
      {"doubleWave", ST_SHAPE_TYPE_DOUBLE_WAVE},
      {"downArrow", ST_SHAPE_TYPE_DOWN_ARROW},
      {"downArrowCallout", ST_SHAPE_TYPE_DOWN_ARROW_CALLOUT},
      {"ellipse", ST_SHAPE_TYPE_ELLIPSE},
      {"ellipseRibbon", ST_SHAPE_TYPE_ELLIPSE_RIBBON},
      {"ellipseRibbon2", ST_SHAPE_TYPE_ELLIPSE_RIBBON2},
      {"flowChartAlternateProcess", ST_SHAPE_TYPE_FLOW_CHART_ALTERNATE_PROCESS},
      {"flowChartCollate", ST_SHAPE_TYPE_FLOW_CHART_COLLATE},
      {"flowChartConnector", ST_SHAPE_TYPE_FLOW_CHART_CONNECTOR},
      {"flowChartDecision", ST_SHAPE_TYPE_FLOW_CHART_DECISION},
      {"flowChartDelay", ST_SHAPE_TYPE_FLOW_CHART_DELAY},
      {"flowChartDisplay", ST_SHAPE_TYPE_FLOW_CHART_DISPLAY},
      {"flowChartDocument", ST_SHAPE_TYPE_FLOW_CHART_DOCUMENT},
      {"flowChartExtract", ST_SHAPE_TYPE_FLOW_CHART_EXTRACT},
      {"flowChartInputOutput", ST_SHAPE_TYPE_FLOW_CHART_INPUT_OUTPUT},
      {"flowChartInternalStorage", ST_SHAPE_TYPE_FLOW_CHART_INTERNAL_STORAGE},
      {"flowChartMagneticDisk", ST_SHAPE_TYPE_FLOW_CHART_MAGNETIC_DISK},
      {"flowChartMagneticDrum", ST_SHAPE_TYPE_FLOW_CHART_MAGNETIC_DRUM},
      {"flowChartMagneticTape", ST_SHAPE_TYPE_FLOW_CHART_MAGNETIC_TAPE},
      {"flowChartManualInput", ST_SHAPE_TYPE_FLOW_CHART_MANUAL_INPUT},
      {"flowChartManualOperation", ST_SHAPE_TYPE_FLOW_CHART_MANUAL_OPERATION},
      {"flowChartMerge", ST_SHAPE_TYPE_FLOW_CHART_MERGE},
      {"flowChartMultidocument", ST_SHAPE_TYPE_FLOW_CHART_MULTIDOCUMENT},
      {"flowChartOfflineStorage", ST_SHAPE_TYPE_FLOW_CHART_OFFLINE_STORAGE},
      {"flowChartOffpageConnector", ST_SHAPE_TYPE_FLOW_CHART_OFFPAGE_CONNECTOR},
      {"flowChartOnlineStorage", ST_SHAPE_TYPE_FLOW_CHART_ONLINE_STORAGE},
      {"flowChartOr", ST_SHAPE_TYPE_FLOW_CHART_OR},
      {"flowChartPredefinedProcess", ST_SHAPE_TYPE_FLOW_CHART_PREDEFINED_PROCESS},
      {"flowChartPreparation", ST_SHAPE_TYPE_FLOW_CHART_PREPARATION},
      {"flowChartProcess", ST_SHAPE_TYPE_FLOW_CHART_PROCESS},
      {"flowChartPunchedCard", ST_SHAPE_TYPE_FLOW_CHART_PUNCHED_CARD},
      {"flowChartPunchedTape", ST_SHAPE_TYPE_FLOW_CHART_PUNCHED_TAPE},
      {"flowChartSort", ST_SHAPE_TYPE_FLOW_CHART_SORT},
      {"flowChartSummingJunction", ST_SHAPE_TYPE_FLOW_CHART_SUMMING_JUNCTION},
      {"flowChartTerminator", ST_SHAPE_TYPE_FLOW_CHART_TERMINATOR},
      {"foldedCorner", ST_SHAPE_TYPE_FOLDED_CORNER},
      {"frame", ST_SHAPE_TYPE_FRAME},
      {"funnel", ST_SHAPE_TYPE_FUNNEL},
      {"gear6", ST_SHAPE_TYPE_GEAR6},
      {"gear9", ST_SHAPE_TYPE_GEAR9},
      {"halfFrame", ST_SHAPE_TYPE_HALF_FRAME},
      {"heart", ST_SHAPE_TYPE_HEART},
      {"heptagon", ST_SHAPE_TYPE_HEPTAGON},
      {"hexagon", ST_SHAPE_TYPE_HEXAGON},
      {"homePlate", ST_SHAPE_TYPE_HOME_PLATE},
      {"horizontalScroll", ST_SHAPE_TYPE_HORIZONTAL_SCROLL},
      {"irregularSeal1", ST_SHAPE_TYPE_IRREGULAR_SEAL1},
      {"irregularSeal2", ST_SHAPE_TYPE_IRREGULAR_SEAL2},
      {"leftArrow", ST_SHAPE_TYPE_LEFT_ARROW},
      {"leftArrowCallout", ST_SHAPE_TYPE_LEFT_ARROW_CALLOUT},
      {"leftBrace", ST_SHAPE_TYPE_LEFT_BRACE},
      {"leftBracket", ST_SHAPE_TYPE_LEFT_BRACKET},
      {"leftCircularArrow", ST_SHAPE_TYPE_LEFT_CIRCULAR_ARROW},
      {"leftRightArrow", ST_SHAPE_TYPE_LEFT_RIGHT_ARROW},
      {"leftRightArrowCallout", ST_SHAPE_TYPE_LEFT_RIGHT_ARROW_CALLOUT},
      {"leftRightCircularArrow", ST_SHAPE_TYPE_LEFT_RIGHT_CIRCULAR_ARROW},
      {"leftRightRibbon", ST_SHAPE_TYPE_LEFT_RIGHT_RIBBON},
      {"leftRightUpArrow", ST_SHAPE_TYPE_LEFT_RIGHT_UP_ARROW},
      {"leftUpArrow", ST_SHAPE_TYPE_LEFT_UP_ARROW},
      {"lightningBolt", ST_SHAPE_TYPE_LIGHTNING_BOLT},
      {"line", ST_SHAPE_TYPE_LINE},
      {"lineInv", ST_SHAPE_TYPE_LINE_INV},
      {"mathDivide", ST_SHAPE_TYPE_MATH_DIVIDE},
      {"mathEqual", ST_SHAPE_TYPE_MATH_EQUAL},
      {"mathMinus", ST_SHAPE_TYPE_MATH_MINUS},
      {"mathMultiply", ST_SHAPE_TYPE_MATH_MULTIPLY},
      {"mathNotEqual", ST_SHAPE_TYPE_MATH_NOT_EQUAL},
      {"mathPlus", ST_SHAPE_TYPE_MATH_PLUS},
      {"moon", ST_SHAPE_TYPE_MOON},
      {"nil", ST_SHAPE_TYPE_NIL},
      {"noSmoking", ST_SHAPE_TYPE_NO_SMOKING},
      {"nonIsoscelesTrapezoid", ST_SHAPE_TYPE_NON_ISOSCELES_TRAPEZOID},
      {"notchedRightArrow", ST_SHAPE_TYPE_NOTCHED_RIGHT_ARROW},
      {"octagon", ST_SHAPE_TYPE_OCTAGON},
      {"parallelogram", ST_SHAPE_TYPE_PARALLELOGRAM},
      {"pentagon", ST_SHAPE_TYPE_PENTAGON},
      {"pie", ST_SHAPE_TYPE_PIE},
      {"pieWedge", ST_SHAPE_TYPE_PIE_WEDGE},
      {"plaque", ST_SHAPE_TYPE_PLAQUE},
      {"plaqueTabs", ST_SHAPE_TYPE_PLAQUE_TABS},
      {"plus", ST_SHAPE_TYPE_PLUS},
      {"quadArrow", ST_SHAPE_TYPE_QUAD_ARROW},
      {"quadArrowCallout", ST_SHAPE_TYPE_QUAD_ARROW_CALLOUT},
      {"rect", ST_SHAPE_TYPE_RECT},
      {"ribbon", ST_SHAPE_TYPE_RIBBON},
      {"ribbon2", ST_SHAPE_TYPE_RIBBON2},
      {"rightArrow", ST_SHAPE_TYPE_RIGHT_ARROW},
      {"rightArrowCallout", ST_SHAPE_TYPE_RIGHT_ARROW_CALLOUT},
      {"rightBrace", ST_SHAPE_TYPE_RIGHT_BRACE},
      {"rightBracket", ST_SHAPE_TYPE_RIGHT_BRACKET},
      {"round1Rect", ST_SHAPE_TYPE_ROUND1_RECT},
      {"round2DiagRect", ST_SHAPE_TYPE_ROUND_2DIAG_RECT},
      {"round2SameRect", ST_SHAPE_TYPE_ROUND2_SAME_RECT},
      {"roundRect", ST_SHAPE_TYPE_ROUND_RECT},
      {"rtTriangle", ST_SHAPE_TYPE_RT_TRIANGLE},
      {"smileyFace", ST_SHAPE_TYPE_SMILEY_FACE},
      {"snip1Rect", ST_SHAPE_TYPE_SNIP1_RECT},
      {"snip2DiagRect", ST_SHAPE_TYPE_SNIP_2DIAG_RECT},
      {"snip2SameRect", ST_SHAPE_TYPE_SNIP2_SAME_RECT},
      {"snipRoundRect", ST_SHAPE_TYPE_SNIP_ROUND_RECT},
      {"squareTabs", ST_SHAPE_TYPE_SQUARE_TABS},
      {"star10", ST_SHAPE_TYPE_STAR10},
      {"star12", ST_SHAPE_TYPE_STAR12},
      {"star16", ST_SHAPE_TYPE_STAR16},
      {"star24", ST_SHAPE_TYPE_STAR24},
      {"star32", ST_SHAPE_TYPE_STAR32},
      {"star4", ST_SHAPE_TYPE_STAR4},
      {"star5", ST_SHAPE_TYPE_STAR5},
      {"star6", ST_SHAPE_TYPE_STAR6},
      {"star7", ST_SHAPE_TYPE_STAR7},
      {"star8", ST_SHAPE_TYPE_STAR8},
      {"straightConnector1", ST_SHAPE_TYPE_STRAIGHT_CONNECTOR1},
      {"stripedRightArrow", ST_SHAPE_TYPE_STRIPED_RIGHT_ARROW},
      {"sun", ST_SHAPE_TYPE_SUN},
      {"swooshArrow", ST_SHAPE_TYPE_SWOOSH_ARROW},
      {"teardrop", ST_SHAPE_TYPE_TEARDROP},
      {"trapezoid", ST_SHAPE_TYPE_TRAPEZOID},
      {"triangle", ST_SHAPE_TYPE_TRIANGLE},
      {"upArrow", ST_SHAPE_TYPE_UP_ARROW},
      {"upArrowCallout", ST_SHAPE_TYPE_UP_ARROW_CALLOUT},
      {"upDownArrow", ST_SHAPE_TYPE_UP_DOWN_ARROW},
      {"upDownArrowCallout", ST_SHAPE_TYPE_UP_DOWN_ARROW_CALLOUT},
      {"uturnArrow", ST_SHAPE_TYPE_UTURN_ARROW},
      {"verticalScroll", ST_SHAPE_TYPE_VERTICAL_SCROLL},
      {"wave", ST_SHAPE_TYPE_WAVE},
      {"wedgeEllipseCallout", ST_SHAPE_TYPE_WEDGE_ELLIPSE_CALLOUT},
      {"wedgeRectCallout", ST_SHAPE_TYPE_WEDGE_RECT_CALLOUT},
      {"wedgeRoundRectCallout", ST_SHAPE_TYPE_WEDGE_ROUND_RECT_CALLOUT}
    };
    // Prepare the key object
    key.key = (char *) pptx_xml_get_attribute_as_string(node, property);
    if (key.key == NULL)
        return ST_SHAPE_TYPE_NIL;
    // Perform binary search
    found = bsearch(&key, base, 188, sizeof key, comparator);
    if (found == NULL) {
        xmlFree(key.key);
        return ST_SHAPE_TYPE_NIL;
    }
    xmlFree(key.key);
    return found->value;
}
