#define __PPTX_PRIVATE_INCLUDES__ /* Allow private includes */
/* Standard headers */
#include <string.h>
/* Self header */
#include <private/pptx-st-preset-color-val.h>
/* Imported internal stuff */

struct map {
    char *key;
    pptx_st_preset_color_val_token_enum value;
};

static int
comparator(const void *const lhs, const void *const rhs)
{
    return strcmp(((struct map *) lhs)->key, ((struct map *) rhs)->key);

}

pptx_st_preset_color_val_token_enum
pptx_get_st_preset_color_val(xmlNode *node, const xmlChar *property)
{
    struct map *found;
    struct map key;
    struct map base[191] = {
      {"aliceBlue", ST_PRESET_COLOR_VAL_ALICE_BLUE},
      {"antiqueWhite", ST_PRESET_COLOR_VAL_ANTIQUE_WHITE},
      {"aqua", ST_PRESET_COLOR_VAL_AQUA},
      {"aquamarine", ST_PRESET_COLOR_VAL_AQUAMARINE},
      {"azure", ST_PRESET_COLOR_VAL_AZURE},
      {"beige", ST_PRESET_COLOR_VAL_BEIGE},
      {"bisque", ST_PRESET_COLOR_VAL_BISQUE},
      {"black", ST_PRESET_COLOR_VAL_BLACK},
      {"blanchedAlmond", ST_PRESET_COLOR_VAL_BLANCHED_ALMOND},
      {"blue", ST_PRESET_COLOR_VAL_BLUE},
      {"blueViolet", ST_PRESET_COLOR_VAL_BLUE_VIOLET},
      {"brown", ST_PRESET_COLOR_VAL_BROWN},
      {"burlyWood", ST_PRESET_COLOR_VAL_BURLY_WOOD},
      {"cadetBlue", ST_PRESET_COLOR_VAL_CADET_BLUE},
      {"chartreuse", ST_PRESET_COLOR_VAL_CHARTREUSE},
      {"chocolate", ST_PRESET_COLOR_VAL_CHOCOLATE},
      {"coral", ST_PRESET_COLOR_VAL_CORAL},
      {"cornflowerBlue", ST_PRESET_COLOR_VAL_CORNFLOWER_BLUE},
      {"cornsilk", ST_PRESET_COLOR_VAL_CORNSILK},
      {"crimson", ST_PRESET_COLOR_VAL_CRIMSON},
      {"cyan", ST_PRESET_COLOR_VAL_CYAN},
      {"darkBlue", ST_PRESET_COLOR_VAL_DARK_BLUE},
      {"darkCyan", ST_PRESET_COLOR_VAL_DARK_CYAN},
      {"darkGoldenrod", ST_PRESET_COLOR_VAL_DARK_GOLDENROD},
      {"darkGray", ST_PRESET_COLOR_VAL_DARK_GRAY},
      {"darkGreen", ST_PRESET_COLOR_VAL_DARK_GREEN},
      {"darkGrey", ST_PRESET_COLOR_VAL_DARK_GREY},
      {"darkKhaki", ST_PRESET_COLOR_VAL_DARK_KHAKI},
      {"darkMagenta", ST_PRESET_COLOR_VAL_DARK_MAGENTA},
      {"darkOliveGreen", ST_PRESET_COLOR_VAL_DARK_OLIVE_GREEN},
      {"darkOrange", ST_PRESET_COLOR_VAL_DARK_ORANGE},
      {"darkOrchid", ST_PRESET_COLOR_VAL_DARK_ORCHID},
      {"darkRed", ST_PRESET_COLOR_VAL_DARK_RED},
      {"darkSalmon", ST_PRESET_COLOR_VAL_DARK_SALMON},
      {"darkSeaGreen", ST_PRESET_COLOR_VAL_DARK_SEA_GREEN},
      {"darkSlateBlue", ST_PRESET_COLOR_VAL_DARK_SLATE_BLUE},
      {"darkSlateGray", ST_PRESET_COLOR_VAL_DARK_SLATE_GRAY},
      {"darkSlateGrey", ST_PRESET_COLOR_VAL_DARK_SLATE_GREY},
      {"darkTurquoise", ST_PRESET_COLOR_VAL_DARK_TURQUOISE},
      {"darkViolet", ST_PRESET_COLOR_VAL_DARK_VIOLET},
      {"deepPink", ST_PRESET_COLOR_VAL_DEEP_PINK},
      {"deepSkyBlue", ST_PRESET_COLOR_VAL_DEEP_SKY_BLUE},
      {"dimGray", ST_PRESET_COLOR_VAL_DIM_GRAY},
      {"dimGrey", ST_PRESET_COLOR_VAL_DIM_GREY},
      {"dkBlue", ST_PRESET_COLOR_VAL_DK_BLUE},
      {"dkCyan", ST_PRESET_COLOR_VAL_DK_CYAN},
      {"dkGoldenrod", ST_PRESET_COLOR_VAL_DK_GOLDENROD},
      {"dkGray", ST_PRESET_COLOR_VAL_DK_GRAY},
      {"dkGreen", ST_PRESET_COLOR_VAL_DK_GREEN},
      {"dkGrey", ST_PRESET_COLOR_VAL_DK_GREY},
      {"dkKhaki", ST_PRESET_COLOR_VAL_DK_KHAKI},
      {"dkMagenta", ST_PRESET_COLOR_VAL_DK_MAGENTA},
      {"dkOliveGreen", ST_PRESET_COLOR_VAL_DK_OLIVE_GREEN},
      {"dkOrange", ST_PRESET_COLOR_VAL_DK_ORANGE},
      {"dkOrchid", ST_PRESET_COLOR_VAL_DK_ORCHID},
      {"dkRed", ST_PRESET_COLOR_VAL_DK_RED},
      {"dkSalmon", ST_PRESET_COLOR_VAL_DK_SALMON},
      {"dkSeaGreen", ST_PRESET_COLOR_VAL_DK_SEA_GREEN},
      {"dkSlateBlue", ST_PRESET_COLOR_VAL_DK_SLATE_BLUE},
      {"dkSlateGray", ST_PRESET_COLOR_VAL_DK_SLATE_GRAY},
      {"dkSlateGrey", ST_PRESET_COLOR_VAL_DK_SLATE_GREY},
      {"dkTurquoise", ST_PRESET_COLOR_VAL_DK_TURQUOISE},
      {"dkViolet", ST_PRESET_COLOR_VAL_DK_VIOLET},
      {"dodgerBlue", ST_PRESET_COLOR_VAL_DODGER_BLUE},
      {"firebrick", ST_PRESET_COLOR_VAL_FIREBRICK},
      {"floralWhite", ST_PRESET_COLOR_VAL_FLORAL_WHITE},
      {"forestGreen", ST_PRESET_COLOR_VAL_FOREST_GREEN},
      {"fuchsia", ST_PRESET_COLOR_VAL_FUCHSIA},
      {"gainsboro", ST_PRESET_COLOR_VAL_GAINSBORO},
      {"ghostWhite", ST_PRESET_COLOR_VAL_GHOST_WHITE},
      {"gold", ST_PRESET_COLOR_VAL_GOLD},
      {"goldenrod", ST_PRESET_COLOR_VAL_GOLDENROD},
      {"gray", ST_PRESET_COLOR_VAL_GRAY},
      {"green", ST_PRESET_COLOR_VAL_GREEN},
      {"greenYellow", ST_PRESET_COLOR_VAL_GREEN_YELLOW},
      {"grey", ST_PRESET_COLOR_VAL_GREY},
      {"honeydew", ST_PRESET_COLOR_VAL_HONEYDEW},
      {"hotPink", ST_PRESET_COLOR_VAL_HOT_PINK},
      {"indianRed", ST_PRESET_COLOR_VAL_INDIAN_RED},
      {"indigo", ST_PRESET_COLOR_VAL_INDIGO},
      {"ivory", ST_PRESET_COLOR_VAL_IVORY},
      {"khaki", ST_PRESET_COLOR_VAL_KHAKI},
      {"lavender", ST_PRESET_COLOR_VAL_LAVENDER},
      {"lavenderBlush", ST_PRESET_COLOR_VAL_LAVENDER_BLUSH},
      {"lawnGreen", ST_PRESET_COLOR_VAL_LAWN_GREEN},
      {"lemonChiffon", ST_PRESET_COLOR_VAL_LEMON_CHIFFON},
      {"lightBlue", ST_PRESET_COLOR_VAL_LIGHT_BLUE},
      {"lightCoral", ST_PRESET_COLOR_VAL_LIGHT_CORAL},
      {"lightCyan", ST_PRESET_COLOR_VAL_LIGHT_CYAN},
      {"lightGoldenrodYellow", ST_PRESET_COLOR_VAL_LIGHT_GOLDENROD_YELLOW},
      {"lightGray", ST_PRESET_COLOR_VAL_LIGHT_GRAY},
      {"lightGreen", ST_PRESET_COLOR_VAL_LIGHT_GREEN},
      {"lightGrey", ST_PRESET_COLOR_VAL_LIGHT_GREY},
      {"lightPink", ST_PRESET_COLOR_VAL_LIGHT_PINK},
      {"lightSalmon", ST_PRESET_COLOR_VAL_LIGHT_SALMON},
      {"lightSeaGreen", ST_PRESET_COLOR_VAL_LIGHT_SEA_GREEN},
      {"lightSkyBlue", ST_PRESET_COLOR_VAL_LIGHT_SKY_BLUE},
      {"lightSlateGray", ST_PRESET_COLOR_VAL_LIGHT_SLATE_GRAY},
      {"lightSlateGrey", ST_PRESET_COLOR_VAL_LIGHT_SLATE_GREY},
      {"lightSteelBlue", ST_PRESET_COLOR_VAL_LIGHT_STEEL_BLUE},
      {"lightYellow", ST_PRESET_COLOR_VAL_LIGHT_YELLOW},
      {"lime", ST_PRESET_COLOR_VAL_LIME},
      {"limeGreen", ST_PRESET_COLOR_VAL_LIME_GREEN},
      {"linen", ST_PRESET_COLOR_VAL_LINEN},
      {"ltBlue", ST_PRESET_COLOR_VAL_LT_BLUE},
      {"ltCoral", ST_PRESET_COLOR_VAL_LT_CORAL},
      {"ltCyan", ST_PRESET_COLOR_VAL_LT_CYAN},
      {"ltGoldenrodYellow", ST_PRESET_COLOR_VAL_LT_GOLDENROD_YELLOW},
      {"ltGray", ST_PRESET_COLOR_VAL_LT_GRAY},
      {"ltGreen", ST_PRESET_COLOR_VAL_LT_GREEN},
      {"ltGrey", ST_PRESET_COLOR_VAL_LT_GREY},
      {"ltPink", ST_PRESET_COLOR_VAL_LT_PINK},
      {"ltSalmon", ST_PRESET_COLOR_VAL_LT_SALMON},
      {"ltSeaGreen", ST_PRESET_COLOR_VAL_LT_SEA_GREEN},
      {"ltSkyBlue", ST_PRESET_COLOR_VAL_LT_SKY_BLUE},
      {"ltSlateGray", ST_PRESET_COLOR_VAL_LT_SLATE_GRAY},
      {"ltSlateGrey", ST_PRESET_COLOR_VAL_LT_SLATE_GREY},
      {"ltSteelBlue", ST_PRESET_COLOR_VAL_LT_STEEL_BLUE},
      {"ltYellow", ST_PRESET_COLOR_VAL_LT_YELLOW},
      {"magenta", ST_PRESET_COLOR_VAL_MAGENTA},
      {"maroon", ST_PRESET_COLOR_VAL_MAROON},
      {"medAquamarine", ST_PRESET_COLOR_VAL_MED_AQUAMARINE},
      {"medBlue", ST_PRESET_COLOR_VAL_MED_BLUE},
      {"medOrchid", ST_PRESET_COLOR_VAL_MED_ORCHID},
      {"medPurple", ST_PRESET_COLOR_VAL_MED_PURPLE},
      {"medSeaGreen", ST_PRESET_COLOR_VAL_MED_SEA_GREEN},
      {"medSlateBlue", ST_PRESET_COLOR_VAL_MED_SLATE_BLUE},
      {"medSpringGreen", ST_PRESET_COLOR_VAL_MED_SPRING_GREEN},
      {"medTurquoise", ST_PRESET_COLOR_VAL_MED_TURQUOISE},
      {"medVioletRed", ST_PRESET_COLOR_VAL_MED_VIOLET_RED},
      {"mediumAquamarine", ST_PRESET_COLOR_VAL_MEDIUM_AQUAMARINE},
      {"mediumBlue", ST_PRESET_COLOR_VAL_MEDIUM_BLUE},
      {"mediumOrchid", ST_PRESET_COLOR_VAL_MEDIUM_ORCHID},
      {"mediumPurple", ST_PRESET_COLOR_VAL_MEDIUM_PURPLE},
      {"mediumSeaGreen", ST_PRESET_COLOR_VAL_MEDIUM_SEA_GREEN},
      {"mediumSlateBlue", ST_PRESET_COLOR_VAL_MEDIUM_SLATE_BLUE},
      {"mediumSpringGreen", ST_PRESET_COLOR_VAL_MEDIUM_SPRING_GREEN},
      {"mediumTurquoise", ST_PRESET_COLOR_VAL_MEDIUM_TURQUOISE},
      {"mediumVioletRed", ST_PRESET_COLOR_VAL_MEDIUM_VIOLET_RED},
      {"midnightBlue", ST_PRESET_COLOR_VAL_MIDNIGHT_BLUE},
      {"mintCream", ST_PRESET_COLOR_VAL_MINT_CREAM},
      {"mistyRose", ST_PRESET_COLOR_VAL_MISTY_ROSE},
      {"moccasin", ST_PRESET_COLOR_VAL_MOCCASIN},
      {"navajoWhite", ST_PRESET_COLOR_VAL_NAVAJO_WHITE},
      {"navy", ST_PRESET_COLOR_VAL_NAVY},
      {"nil", ST_PRESET_COLOR_VAL_NIL},
      {"oldLace", ST_PRESET_COLOR_VAL_OLD_LACE},
      {"olive", ST_PRESET_COLOR_VAL_OLIVE},
      {"oliveDrab", ST_PRESET_COLOR_VAL_OLIVE_DRAB},
      {"orange", ST_PRESET_COLOR_VAL_ORANGE},
      {"orangeRed", ST_PRESET_COLOR_VAL_ORANGE_RED},
      {"orchid", ST_PRESET_COLOR_VAL_ORCHID},
      {"paleGoldenrod", ST_PRESET_COLOR_VAL_PALE_GOLDENROD},
      {"paleGreen", ST_PRESET_COLOR_VAL_PALE_GREEN},
      {"paleTurquoise", ST_PRESET_COLOR_VAL_PALE_TURQUOISE},
      {"paleVioletRed", ST_PRESET_COLOR_VAL_PALE_VIOLET_RED},
      {"papayaWhip", ST_PRESET_COLOR_VAL_PAPAYA_WHIP},
      {"peachPuff", ST_PRESET_COLOR_VAL_PEACH_PUFF},
      {"peru", ST_PRESET_COLOR_VAL_PERU},
      {"pink", ST_PRESET_COLOR_VAL_PINK},
      {"plum", ST_PRESET_COLOR_VAL_PLUM},
      {"powderBlue", ST_PRESET_COLOR_VAL_POWDER_BLUE},
      {"purple", ST_PRESET_COLOR_VAL_PURPLE},
      {"red", ST_PRESET_COLOR_VAL_RED},
      {"rosyBrown", ST_PRESET_COLOR_VAL_ROSY_BROWN},
      {"royalBlue", ST_PRESET_COLOR_VAL_ROYAL_BLUE},
      {"saddleBrown", ST_PRESET_COLOR_VAL_SADDLE_BROWN},
      {"salmon", ST_PRESET_COLOR_VAL_SALMON},
      {"sandyBrown", ST_PRESET_COLOR_VAL_SANDY_BROWN},
      {"seaGreen", ST_PRESET_COLOR_VAL_SEA_GREEN},
      {"seaShell", ST_PRESET_COLOR_VAL_SEA_SHELL},
      {"sienna", ST_PRESET_COLOR_VAL_SIENNA},
      {"silver", ST_PRESET_COLOR_VAL_SILVER},
      {"skyBlue", ST_PRESET_COLOR_VAL_SKY_BLUE},
      {"slateBlue", ST_PRESET_COLOR_VAL_SLATE_BLUE},
      {"slateGray", ST_PRESET_COLOR_VAL_SLATE_GRAY},
      {"slateGrey", ST_PRESET_COLOR_VAL_SLATE_GREY},
      {"snow", ST_PRESET_COLOR_VAL_SNOW},
      {"springGreen", ST_PRESET_COLOR_VAL_SPRING_GREEN},
      {"steelBlue", ST_PRESET_COLOR_VAL_STEEL_BLUE},
      {"tan", ST_PRESET_COLOR_VAL_TAN},
      {"teal", ST_PRESET_COLOR_VAL_TEAL},
      {"thistle", ST_PRESET_COLOR_VAL_THISTLE},
      {"tomato", ST_PRESET_COLOR_VAL_TOMATO},
      {"turquoise", ST_PRESET_COLOR_VAL_TURQUOISE},
      {"violet", ST_PRESET_COLOR_VAL_VIOLET},
      {"wheat", ST_PRESET_COLOR_VAL_WHEAT},
      {"white", ST_PRESET_COLOR_VAL_WHITE},
      {"whiteSmoke", ST_PRESET_COLOR_VAL_WHITE_SMOKE},
      {"yellow", ST_PRESET_COLOR_VAL_YELLOW},
      {"yellowGreen", ST_PRESET_COLOR_VAL_YELLOW_GREEN}
    };
    // Prepare the key object
    key.key = (char *) pptx_xml_get_attribute_as_string(node, property);
    if (key.key == NULL)
        return ST_PRESET_COLOR_VAL_NIL;
    // Perform binary search
    found = bsearch(&key, base, 191, sizeof key, comparator);
    if (found == NULL) {
        xmlFree(key.key);
        return ST_PRESET_COLOR_VAL_NIL;
    }
    xmlFree(key.key);
    return found->value;
}
